@LICENSE@
// This file has been generated by the metapod robotbuilder library.

#ifndef @LIBRARY_NAME@_BODY_HH
# define @LIBRARY_NAME@_BODY_HH

# include "metapod/tools/bodymacros.hh"

namespace metapod {
namespace @ROBOT_NAMESPACE@ {

@body_definitions@

} // closing namespace @ROBOT_NAMESPACE@
} // closing namespace metapod
#endif
