@LICENSE@
// This file has been generated by the metapod robotbuilder library.

#include "@ROBOT_NAME@.hh"

namespace metapod {

@init_nodes@

Spatial::Inertia @ROBOT_CLASS_NAME@::inertias[@node_id@] = {
@init_inertias@};
}
