@LICENSE@
// This file has been generated by the metapod robotbuilder library.

#ifndef @LIBRARY_NAME@_JOINT_HH
# define @LIBRARY_NAME@_JOINT_HH

# include "metapod/tools/jointmacros.hh"

namespace metapod {
namespace @ROBOT_NAMESPACE@ {

@joint_definitions@

} // closing namespace @ROBOT_NAMESPACE@
} // closing namespace metapod
#endif
