@LICENSE@
// This file has been generated by the metapod robotbuilder library.

#ifndef @LIBRARY_NAME@_ROBOT_HH
# define @LIBRARY_NAME@_ROBOT_HH

# include "config.hh"
# include "metapod/tools/common.hh"
# include "joint.hh"
# include "body.hh"

namespace metapod {
namespace @ROBOT_NAMESPACE@ {

class @LIBRARY_NAME@_DLLAPI Robot {
public:
  // Global constants or variable of the robot
  enum { NBDOF = @ROBOT_NB_DOF@ };
  enum { NBBODIES = @ROBOT_NB_BODIES@ };
  static Eigen::Matrix< FloatType, NBDOF, NBDOF > H;
  typedef Eigen::Matrix< FloatType, NBDOF, 1 > confVector;

  // Definition of the multibody tree as a type.
  typedef
  @nodes_tree@ Tree;
};

} // closing namespace @ROBOT_NAMESPACE@
} // closing namespace metapod
#endif
