// Copyright 2011, 2012, 2013
//
// Maxime Reis (JRL/LAAS, CNRS/AIST)
// Sébastien Barthélémy (Aldebaran Robotics)
//
// This file is part of metapod.
// metapod is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// metapod is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// You should have received a copy of the GNU Lesser General Public License
// along with metapod.  If not, see <http://www.gnu.org/licenses/>.


// This file has been generated by the metapod robotbuilder library.
#ifndef METAPOD_SIMPLE_ARM_CONFIG_HH
# define METAPOD_SIMPLE_ARM_CONFIG_HH

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define METAPOD_SIMPLE_ARM_DLLIMPORT __declspec(dllimport)
#  define METAPOD_SIMPLE_ARM_DLLEXPORT __declspec(dllexport)
#  define METAPOD_SIMPLE_ARM_DLLLOCAL
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define METAPOD_SIMPLE_ARM_DLLIMPORT __attribute__ ((visibility("default")))
#   define METAPOD_SIMPLE_ARM_DLLEXPORT __attribute__ ((visibility("default")))
#   define METAPOD_SIMPLE_ARM_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define METAPOD_SIMPLE_ARM_DLLIMPORT
#   define METAPOD_SIMPLE_ARM_DLLEXPORT
#   define METAPOD_SIMPLE_ARM_DLLLOCAL
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef METAPOD_SIMPLE_ARM_STATIC
// If one is using the library statically, get rid of
// extra information.
#  define METAPOD_SIMPLE_ARM_DLLAPI
#  define METAPOD_SIMPLE_ARM_LOCAL
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export.
#  ifdef metapod_simple_arm_EXPORTS
#   define METAPOD_SIMPLE_ARM_DLLAPI METAPOD_SIMPLE_ARM_DLLEXPORT
#  else
#   define METAPOD_SIMPLE_ARM_DLLAPI METAPOD_SIMPLE_ARM_DLLIMPORT
#  endif // METAPOD_SIMPLE_ARM_EXPORTS
#  define METAPOD_SIMPLE_ARM_LOCAL METAPOD_SIMPLE_ARM_DLLLOCAL
# endif // METAPOD_SIMPLE_ARM_STATIC
#endif //! METAPOD_SIMPLE_ARM_CONFIG_HH

