metapod::Spatial::TransformT< RotationClass > Class Template Reference
metapod::Spatial::TransformT< RotationClass > Class Template Reference
Given two frames a and b, one can define the transform bXa, which changes coordinates between the two.
#include <metapod/tools/spatial/transform.hh>
Public Member Functions
TransformT ()
TransformT (const Matrix3d &E, const Vector3d &r)
TransformT (const RotationClass &E, const Vector3d &r)
const Vector3d & r () const
const RotationClass & E () const
Motion apply (const Motion &mv) const
Vb = bXa.apply(Va)
Force apply (const Force &fv) const
Fb = bXa.apply(Fa)
Inertia apply (const Inertia &I) const
Ib = bXa.apply(Ia)
Vector3d apply (const Vector3d &p) const
Pb = bXa.apply(Pa)
Vector6d apply (const ConstraintMotionAnyAxis &S) const
Sb = bXa.apply(Sa)
Vector6d apply (const ConstraintMotionAxisX &) const
Sb = bXa.apply(Sa)
Vector6d apply (const ConstraintMotionAxisY &) const
Sb = bXa.apply(Sa)
Vector6d apply (const ConstraintMotionAxisZ &) const
Sb = bXa.apply(Sa)
Matrix6d apply (const ConstraintMotionFreeFlyer &S) const
Sb = bXa.apply(Sa)
Matrix6d toMatrix () const
Vb.toVector() = bXa.toMatrix() * Va.toVector()
Matrix6d toMatrixTranspose () const
Fa.toVector() = bXa.toMatrixTranspose() * Fb.toVector()
Matrix6d toMatrixTransposeInverse () const
Fb.toVector() = bXa.toMatrixTransposeInverse() * Fa.toVector()
Motion applyInv (const Motion &mv) const
Va = bXa.applyInv(Vb)
Force applyInv (const Force &fv) const
Fa = bXa.applyInv(Fb)
Inertia applyInv (const Inertia &I) const
Ia = bXa.applyInv(Ib)
Vector3d applyInv (const Vector3d &p) const
Pa = bXa.applyInv(Pb)
Vector6d mulMatrixTransposeBy (Vector6d &aF) const
TransformT inverse () const
aXb = bXa.inverse()
TransformT operator* (FloatType a) const
TransformT operator* (const TransformT &X) const
TransformT toPointFrame (const Vector3d &p) const
Specialization of transform multiplication.
Motion operator* (const Motion &mv) const
Vb = bXa * Va.
Force operator* (const Force &fv) const
Fb = bXa * Fa.
Inertia operator* (const Inertia &I) const
Ib = bXa * Ia.
template<class S >
TransformT< typename rm_mul_op
< RotationClass, S >::rm > operator* (const TransformT< S > &aTsf) const
template<>
Vector6d mulMatrixTransposeBy (Vector6d &aF) const
template<>
Vector6d mulMatrixTransposeBy (Vector6d &aF) const
template<>
Vector6d mulMatrixTransposeBy (Vector6d &aF) const
template<>
Vector6d mulMatrixTransposeBy (Vector6d &aF) const
Static Public Member Functions
static const TransformT Identity ()
Friends
std::ostream & operator<< (std::ostream &os, const TransformT &X)
Detailed Description
template<class RotationClass>
class metapod::Spatial::TransformT< RotationClass >
Given two frames a and b, one can define the transform bXa, which changes coordinates between the two.
bXa is composed of a rotation matrix E, which changes vector coordinates from a to b, and a vector r, which gives the position of the origin of b, expressed in the a frame. So if v is a vector and p is a point, we have:
vb = bXa.E * va pb = bXa.E * (pa - bXa.r)
Constructor & Destructor Documentation
template<class RotationClass> metapod::Spatial::TransformT< RotationClass >::TransformT () [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::Identity(), metapod::Spatial::TransformT< RotationClass >::inverse(), metapod::Spatial::TransformT< RotationClass >::operator*(), and metapod::Spatial::TransformT< RotationClass >::toPointFrame().
template<class RotationClass> metapod::Spatial::TransformT< RotationClass >::TransformT (const Matrix3d & E, const Vector3d & r) [inline]
template<class RotationClass> metapod::Spatial::TransformT< RotationClass >::TransformT (const RotationClass & E, const Vector3d & r) [inline]
Member Function Documentation
template<class RotationClass> Motion metapod::Spatial::TransformT< RotationClass >::apply (const Motion & mv) const [inline]
Vb = bXa.apply(Va)
References metapod::Spatial::Motion::v(), and metapod::Spatial::Motion::w().
template<class RotationClass> Force metapod::Spatial::TransformT< RotationClass >::apply (const Force & fv) const [inline]
Fb = bXa.apply(Fa)
References metapod::Spatial::Force::f(), and metapod::Spatial::Force::n().
template<class RotationClass> Inertia metapod::Spatial::TransformT< RotationClass >::apply (const Inertia & I) const [inline]
Ib = bXa.apply(Ia)
References metapod::Spatial::Inertia::h(), metapod::Spatial::Inertia::I(), metapod::Spatial::Inertia::m(), and metapod::Spatial::skew().
template<class RotationClass> Vector3d metapod::Spatial::TransformT< RotationClass >::apply (const Vector3d & p) const [inline]
Pb = bXa.apply(Pa)
template<class RotationClass> Vector6d metapod::Spatial::TransformT< RotationClass >::apply (const ConstraintMotionAnyAxis & S) const [inline]
Sb = bXa.apply(Sa)
Specialization for JOINT_REVOLUTE_AXIS_ANY
References metapod::Spatial::ConstraintMotionAnyAxis::S().
template<class RotationClass> Vector6d metapod::Spatial::TransformT< RotationClass >::apply (const ConstraintMotionAxisX &) const [inline]
Sb = bXa.apply(Sa)
Specialization for JOINT_REVOLUTE_AXIS_X
template<class RotationClass> Vector6d metapod::Spatial::TransformT< RotationClass >::apply (const ConstraintMotionAxisY &) const [inline]
Sb = bXa.apply(Sa)
Specialization for JOINT_REVOLUTE_AXIS_Y
template<class RotationClass> Vector6d metapod::Spatial::TransformT< RotationClass >::apply (const ConstraintMotionAxisZ &) const [inline]
Sb = bXa.apply(Sa)
Specialization for JOINT_REVOLUTE_AXIS_Z
template<class RotationClass> Matrix6d metapod::Spatial::TransformT< RotationClass >::apply (const ConstraintMotionFreeFlyer & S) const [inline]
Sb = bXa.apply(Sa)
Specialization for JOINT_FREE_FLYER
References metapod::Spatial::ConstraintMotionFreeFlyer::S(), and metapod::Spatial::skew().
template<class RotationClass> Motion metapod::Spatial::TransformT< RotationClass >::applyInv (const Motion & mv) const [inline]
Va = bXa.applyInv(Vb)
References metapod::Spatial::Motion::v(), and metapod::Spatial::Motion::w().
template<class RotationClass> Force metapod::Spatial::TransformT< RotationClass >::applyInv (const Force & fv) const [inline]
Fa = bXa.applyInv(Fb)
References metapod::Spatial::Force::f(), and metapod::Spatial::Force::n().
template<class RotationClass> Inertia metapod::Spatial::TransformT< RotationClass >::applyInv (const Inertia & I) const [inline]
Ia = bXa.applyInv(Ib)
References metapod::Spatial::Inertia::h(), metapod::Spatial::Inertia::I(), metapod::Spatial::Inertia::m(), and metapod::Spatial::skew().
template<class RotationClass> Vector3d metapod::Spatial::TransformT< RotationClass >::applyInv (const Vector3d & p) const [inline]
Pa = bXa.applyInv(Pb)
template<class RotationClass> const RotationClass& metapod::Spatial::TransformT< RotationClass >::E () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::operator*(), and metapod::internal::jac_point_chain_internal_freeflyer< Robot, start_node_id, end_node_id, offset, true >::run().
template<class RotationClass> static const TransformT metapod::Spatial::TransformT< RotationClass >::Identity () [inline, static]
References metapod::Spatial::TransformT< RotationClass >::TransformT().
template<class RotationClass> TransformT metapod::Spatial::TransformT< RotationClass >::inverse () const [inline]
aXb = bXa.inverse()
References metapod::Spatial::TransformT< RotationClass >::TransformT().
Referenced by metapod::internal::jac_point_chain_internal_freeflyer< Robot, start_node_id, end_node_id, offset, true >::run().
template<class RotationClass> Vector6d metapod::Spatial::TransformT< RotationClass >::mulMatrixTransposeBy (Vector6d & aF) const
template<> Vector6d metapod::Spatial::TransformT< RotationMatrixAboutX >::mulMatrixTransposeBy (Vector6d & aF) const [inline]
template<> Vector6d metapod::Spatial::TransformT< RotationMatrixAboutY >::mulMatrixTransposeBy (Vector6d & aF) const [inline]
template<> Vector6d metapod::Spatial::TransformT< RotationMatrixAboutZ >::mulMatrixTransposeBy (Vector6d & aF) const [inline]
template<> Vector6d metapod::Spatial::TransformT< RotationMatrix >::mulMatrixTransposeBy (Vector6d & aF) const [inline]
template<class RotationClass> TransformT metapod::Spatial::TransformT< RotationClass >::operator* (FloatType a) const [inline]
References metapod::Spatial::TransformT< RotationClass >::TransformT().
template<class RotationClass> TransformT metapod::Spatial::TransformT< RotationClass >::operator* (const TransformT< RotationClass > & X) const [inline]
References metapod::Spatial::TransformT< RotationClass >::E(), metapod::Spatial::TransformT< RotationClass >::r(), and metapod::Spatial::TransformT< RotationClass >::TransformT().
template<class RotationClass> Motion metapod::Spatial::TransformT< RotationClass >::operator* (const Motion & mv) const [inline]
Vb = bXa * Va.
References metapod::Spatial::Motion::v(), and metapod::Spatial::Motion::w().
template<class RotationClass> Force metapod::Spatial::TransformT< RotationClass >::operator* (const Force & fv) const [inline]
Fb = bXa * Fa.
References metapod::Spatial::Force::f(), and metapod::Spatial::Force::n().
template<class RotationClass> Inertia metapod::Spatial::TransformT< RotationClass >::operator* (const Inertia & I) const [inline]
Ib = bXa * Ia.
References metapod::Spatial::Inertia::h(), metapod::Spatial::Inertia::I(), metapod::Spatial::Inertia::m(), and metapod::Spatial::skew().
template<class RotationClass> template<class S > TransformT< typename rm_mul_op<RotationClass,S>::rm > metapod::Spatial::TransformT< RotationClass >::operator* (const TransformT< S > & aTsf) const [inline]
References metapod::Spatial::TransformT< RotationClass >::E(), and metapod::Spatial::TransformT< RotationClass >::r().
template<class RotationClass> const Vector3d& metapod::Spatial::TransformT< RotationClass >::r () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::operator*(), and metapod::internal::jac_point_chain_internal_freeflyer< Robot, start_node_id, end_node_id, offset, true >::run().
template<class RotationClass> Matrix6d metapod::Spatial::TransformT< RotationClass >::toMatrix () const [inline]
Vb.toVector() = bXa.toMatrix() * Va.toVector()
References metapod::Spatial::skew().
template<class RotationClass> Matrix6d metapod::Spatial::TransformT< RotationClass >::toMatrixTranspose () const [inline]
Fa.toVector() = bXa.toMatrixTranspose() * Fb.toVector()
References metapod::Spatial::skew().
template<class RotationClass> Matrix6d metapod::Spatial::TransformT< RotationClass >::toMatrixTransposeInverse () const [inline]
Fb.toVector() = bXa.toMatrixTransposeInverse() * Fa.toVector()
References metapod::Spatial::skew().
template<class RotationClass> TransformT metapod::Spatial::TransformT< RotationClass >::toPointFrame (const Vector3d & p) const [inline]
Specialization of transform multiplication.
Compute transform cXa from bXa, with cXb a translation defined by the vector Pb (expressed in frame b).
In a nutshell:
cXb == TransformT(Eye, Pb) cXa == cXb * bXa == bXa.toPointFrame(Pb)
References metapod::Spatial::TransformT< RotationClass >::TransformT().
Referenced by metapod::internal::jac_point_chain_internal_freeflyer< Robot, start_node_id, end_node_id, offset, true >::run().
Friends And Related Function Documentation
template<class RotationClass> std::ostream& operator<< (std::ostream & os, const TransformT< RotationClass > & X) [friend]