metapod::FreeFlyerJoint Class Reference
metapod::FreeFlyerJoint Class Reference
#include <metapod/tools/joint-freeflyer.hh>
Public Member Functions
FreeFlyerJoint ()
void bcalc (const Vector6d &qi)
void jcalc (const Vector6d &qi, const Vector6d &dqi)
Public Attributes
Spatial::Transform Xj
Spatial::Motion cj
Spatial::Motion vj
Spatial::ConstraintMotionFreeFlyer S
Spatial::Force f
Vector6d torque
Static Public Attributes
static const int NBDOF = 6
Constructor & Destructor Documentation
metapod::FreeFlyerJoint::FreeFlyerJoint () [inline]
Member Function Documentation
void metapod::FreeFlyerJoint::bcalc (const Vector6d & qi) [inline]
References S, metapod::Spatial::ConstraintMotionFreeFlyer::setlocalR(), and Xj.
Referenced by jcalc().
void metapod::FreeFlyerJoint::jcalc (const Vector6d & qi, const Vector6d & dqi) [inline]
References bcalc(), cj, S, metapod::Spatial::ConstraintMotionFreeFlyer::S(), metapod::Spatial::skew(), and vj.
Member Data Documentation
Spatial::Motion metapod::FreeFlyerJoint::cj
Referenced by jcalc().
Spatial::Force metapod::FreeFlyerJoint::f
const int metapod::FreeFlyerJoint::NBDOF = 6 [static]
Spatial::ConstraintMotionFreeFlyer metapod::FreeFlyerJoint::S
Referenced by bcalc(), and jcalc().
Vector6d metapod::FreeFlyerJoint::torque
Spatial::Motion metapod::FreeFlyerJoint::vj
Referenced by jcalc().
Spatial::Transform metapod::FreeFlyerJoint::Xj
Referenced by bcalc().