metapod::Spatial::MotionTpl< FloatType > Class Template Reference
metapod::Spatial::MotionTpl< FloatType > Class Template Reference
#include <metapod/tools/spatial/motion.hh>
Public Member Functions
MotionTpl ()
MotionTpl (const Vector3d &w, const Vector3d &v)
MotionTpl (const Vector6d &v)
const Vector3d & w () const
const Vector3d & v () const
void w (const Vector3d &v)
void v (const Vector3d &v)
MotionTpl & operator= (const Vector6d &v)
MotionTpl operator- () const
MotionTpl operator+ (const MotionTpl &mv) const
MotionTpl operator* (FloatType a) const
MotionTpl operator^ (const MotionTpl &mv) const
Force operator^ (const Force &fv) const
Static Public Member Functions
static const MotionTpl Zero ()
Friends
MotionTpl operator* (FloatType a, const MotionTpl &mv)
std::ostream & operator<< (std::ostream &os, const MotionTpl &mv)
template<class FloatType>
class metapod::Spatial::MotionTpl< FloatType >
Constructor & Destructor Documentation
template<class FloatType> metapod::Spatial::MotionTpl< FloatType >::MotionTpl () [inline]
Referenced by metapod::Spatial::MotionTpl< FloatType >::operator*(), metapod::Spatial::MotionTpl< FloatType >::operator+(), metapod::Spatial::MotionTpl< FloatType >::operator-(), metapod::Spatial::MotionTpl< FloatType >::operator^(), and metapod::Spatial::MotionTpl< FloatType >::Zero().
template<class FloatType> metapod::Spatial::MotionTpl< FloatType >::MotionTpl (const Vector3d & w, const Vector3d & v) [inline]
template<class FloatType> metapod::Spatial::MotionTpl< FloatType >::MotionTpl (const Vector6d & v) [inline]
Member Function Documentation
template<class FloatType> MotionTpl metapod::Spatial::MotionTpl< FloatType >::operator* (FloatType a) const [inline]
References metapod::Spatial::MotionTpl< FloatType >::MotionTpl().
template<class FloatType> MotionTpl metapod::Spatial::MotionTpl< FloatType >::operator+ (const MotionTpl< FloatType > & mv) const [inline]
References metapod::Spatial::MotionTpl< FloatType >::MotionTpl(), metapod::Spatial::MotionTpl< FloatType >::v(), and metapod::Spatial::MotionTpl< FloatType >::w().
template<class FloatType> MotionTpl metapod::Spatial::MotionTpl< FloatType >::operator- () const [inline]
References metapod::Spatial::MotionTpl< FloatType >::MotionTpl().
template<class FloatType> MotionTpl& metapod::Spatial::MotionTpl< FloatType >::operator= (const Vector6d & v) [inline]
template<class FloatType> MotionTpl metapod::Spatial::MotionTpl< FloatType >::operator^ (const MotionTpl< FloatType > & mv) const [inline]
References metapod::Spatial::MotionTpl< FloatType >::MotionTpl(), metapod::Spatial::MotionTpl< FloatType >::v(), and metapod::Spatial::MotionTpl< FloatType >::w().
template<class FloatType> Force metapod::Spatial::MotionTpl< FloatType >::operator^ (const Force & fv) const [inline]
template<class FloatType> const Vector3d& metapod::Spatial::MotionTpl< FloatType >::v () const [inline]
Referenced by metapod::Spatial::MotionTpl< FloatType >::operator+(), metapod::Spatial::MotionTpl< FloatType >::operator^(), metapod::Spatial::sum(), and metapod::Spatial::MotionTpl< FloatType >::w().
template<class FloatType> void metapod::Spatial::MotionTpl< FloatType >::v (const Vector3d & v) [inline]
References metapod::Spatial::MotionTpl< FloatType >::v().
Referenced by metapod::Spatial::MotionTpl< FloatType >::v().
template<class FloatType> const Vector3d& metapod::Spatial::MotionTpl< FloatType >::w () const [inline]
Referenced by metapod::Spatial::MotionTpl< FloatType >::operator+(), metapod::Spatial::MotionTpl< FloatType >::operator^(), and metapod::Spatial::sum().
template<class FloatType> void metapod::Spatial::MotionTpl< FloatType >::w (const Vector3d & v) [inline]
References metapod::Spatial::MotionTpl< FloatType >::v().
template<class FloatType> static const MotionTpl metapod::Spatial::MotionTpl< FloatType >::Zero () [inline, static]
References metapod::Spatial::MotionTpl< FloatType >::MotionTpl().
Friends And Related Function Documentation
template<class FloatType> MotionTpl operator* (FloatType a, const MotionTpl< FloatType > & mv) [friend]
template<class FloatType> std::ostream& operator<< (std::ostream & os, const MotionTpl< FloatType > & mv) [friend]