metapod::RevoluteAxisAnyJoint Class Reference
metapod::RevoluteAxisAnyJoint Class Reference
#include <metapod/tools/joint-anyaxis.hh>
Public Member Functions
RevoluteAxisAnyJoint (double axis_x, double axis_y, double axis_z)
void bcalc (const Vector1d &qi)
void jcalc (const Vector1d &qi, const Vector1d &dqi)
Public Attributes
Spatial::Transform Xj
Spatial::Motion cj
Spatial::Motion vj
Spatial::ConstraintMotionAnyAxis S
Spatial::Force f
Vector1d torque
const Vector3d axis_
Static Public Attributes
static const int NBDOF = 1
Constructor & Destructor Documentation
metapod::RevoluteAxisAnyJoint::RevoluteAxisAnyJoint (double axis_x, double axis_y, double axis_z) [inline]
References metapod::Spatial::Motion::v(), and vj.
Member Function Documentation
void metapod::RevoluteAxisAnyJoint::bcalc (const Vector1d & qi) [inline]
References axis_, and Xj.
Referenced by jcalc().
void metapod::RevoluteAxisAnyJoint::jcalc (const Vector1d & qi, const Vector1d & dqi) [inline]
References axis_, bcalc(), vj, and metapod::Spatial::Motion::w().
Member Data Documentation
const Vector3d metapod::RevoluteAxisAnyJoint::axis_
Referenced by bcalc(), and jcalc().
Spatial::Motion metapod::RevoluteAxisAnyJoint::cj
Spatial::Force metapod::RevoluteAxisAnyJoint::f
const int metapod::RevoluteAxisAnyJoint::NBDOF = 1 [static]
Spatial::ConstraintMotionAnyAxis metapod::RevoluteAxisAnyJoint::S
Vector1d metapod::RevoluteAxisAnyJoint::torque
Spatial::Motion metapod::RevoluteAxisAnyJoint::vj
Referenced by jcalc(), and RevoluteAxisAnyJoint().
Spatial::Transform metapod::RevoluteAxisAnyJoint::Xj
Referenced by bcalc().