metapod::Spatial::Inertia Class Reference
metapod::Spatial::Inertia Class Reference
#include <metapod/tools/spatial/inertia.hh>
Public Member Functions
Inertia ()
Inertia (FloatType m, const Vector3d &h, const Matrix3d &I)
Inertia (FloatType m, const Vector3d &h, const lowerTriangularMatrix &I)
FloatType m () const
const Vector3d & h () const
const lowerTriangularMatrix & I () const
Matrix6d toMatrix () const
Inertia operator+ (const Inertia &other) const
Static Public Member Functions
static const Inertia Zero ()
Friends
class OperatorMul
Inertia operator* (FloatType a, const Inertia &I)
std::ostream & operator<< (std::ostream &os, const Inertia &I)
template<class T , class U , class S >
T operator* (const U &u, const S &s)
Constructor & Destructor Documentation
metapod::Spatial::Inertia::Inertia () [inline]
Referenced by operator+(), and Zero().
metapod::Spatial::Inertia::Inertia (FloatType m, const Vector3d & h, const Matrix3d & I) [inline]
metapod::Spatial::Inertia::Inertia (FloatType m, const Vector3d & h, const lowerTriangularMatrix & I) [inline]
Member Function Documentation
const Vector3d& metapod::Spatial::Inertia::h () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::apply(), metapod::Spatial::TransformT< RotationClass >::applyInv(), metapod::Spatial::OperatorMul< T, U, S >::mul(), metapod::Spatial::operator*(), metapod::Spatial::TransformT< RotationClass >::operator*(), and operator+().
const lowerTriangularMatrix& metapod::Spatial::Inertia::I () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::apply(), metapod::Spatial::TransformT< RotationClass >::applyInv(), metapod::Spatial::OperatorMul< T, U, S >::mul(), metapod::Spatial::operator*(), metapod::Spatial::TransformT< RotationClass >::operator*(), and operator+().
FloatType metapod::Spatial::Inertia::m () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::apply(), metapod::Spatial::TransformT< RotationClass >::applyInv(), metapod::Spatial::OperatorMul< T, U, S >::mul(), metapod::Spatial::TransformT< RotationClass >::operator*(), and operator+().
Inertia metapod::Spatial::Inertia::operator+ (const Inertia & other) const [inline]
References h(), I(), Inertia(), and m().
Matrix6d metapod::Spatial::Inertia::toMatrix () const [inline]
References metapod::Spatial::skew(), and metapod::Spatial::ltI::toMatrix().
static const Inertia metapod::Spatial::Inertia::Zero () [inline, static]
References Inertia(), and metapod::Spatial::ltI::Zero().
Friends And Related Function Documentation
Inertia operator* (FloatType a, const Inertia & I) [friend]
template<class T , class U , class S > T operator* (const U & u, const S & s) [friend]
std::ostream& operator<< (std::ostream & os, const Inertia & I) [friend]
friend class OperatorMul [friend]