metapod::Spatial::RotationMatrixChangeAxis< traits > Struct Template Reference
metapod::Spatial::RotationMatrixChangeAxis< traits > Struct Template Reference
Rotation matrix as axis permutation matrix.
#include <metapod/tools/spatial/rm-chgaxis.hh>
Public Types
typedef traits Traits
Public Member Functions
RotationMatrixChangeAxis ()
RotationMatrixChangeAxis (const RotationMatrixChangeAxis &)
RotationMatrixChangeAxis transpose () const
Matrix3d toMatrix ()
Matrix3d operator* (FloatType a) const
void randomInit ()
RotationMatrixChangeAxis operator- () const
Matrix3d operator* (const Matrix3d &A) const
template<typename traits_rhs >
RotationMatrixChangeAxis
< rmca_traits_mul< traits,
traits_rhs > > operator* (const RotationMatrixChangeAxis< traits_rhs > &)
RotationMatrix operator* (const RotationMatrix &aRM) const
RotationMatrix operator* (const RotationMatrixAboutX &aRM) const
RotationMatrix operator* (const RotationMatrixAboutY &aRM) const
RotationMatrix operator* (const RotationMatrixAboutZ &aRM) const
Matrix3d rotGeneralMatrix (const Matrix3d &A) const
ltI rotSymmetricMatrix (const ltI &A)
ltI rotTSymmetricMatrix (const ltI &A)
Vector3d operator* (const Vector3d &ar) const
Friends
Matrix3d operator* (const Matrix3d &A, const RotationMatrixChangeAxis &aRMCA)
std::ostream & operator<< (std::ostream &os, const RotationMatrixChangeAxis< traits > &aRMCA)
Detailed Description
template<typename traits>
struct metapod::Spatial::RotationMatrixChangeAxis< traits >
Rotation matrix as axis permutation matrix.
This matrix is defined by 7 parameters: .
Member Typedef Documentation
template<typename traits> typedef traits metapod::Spatial::RotationMatrixChangeAxis< traits >::Traits
Constructor & Destructor Documentation
template<typename traits> metapod::Spatial::RotationMatrixChangeAxis< traits >::RotationMatrixChangeAxis () [inline]
template<typename traits> metapod::Spatial::RotationMatrixChangeAxis< traits >::RotationMatrixChangeAxis (const RotationMatrixChangeAxis< traits > &) [inline]
Member Function Documentation
template<typename traits> Matrix3d metapod::Spatial::RotationMatrixChangeAxis< traits >::operator* (FloatType a) const [inline]
References metapod::Spatial::RotationMatrixChangeAxis< traits >::toMatrix().
template<typename traits> Matrix3d metapod::Spatial::RotationMatrixChangeAxis< traits >::operator* (const Matrix3d & A) const [inline]
template<typename traits> template<typename traits_rhs > RotationMatrixChangeAxis< rmca_traits_mul<traits,traits_rhs> > metapod::Spatial::RotationMatrixChangeAxis< traits >::operator* (const RotationMatrixChangeAxis< traits_rhs > &) [inline]
template<typename traits> RotationMatrix metapod::Spatial::RotationMatrixChangeAxis< traits >::operator* (const RotationMatrix & aRM) const [inline]
References metapod::Spatial::RotationMatrix::m_rm.
template<typename traits> RotationMatrix metapod::Spatial::RotationMatrixChangeAxis< traits >::operator* (const RotationMatrixAboutX & aRM) const [inline]
References metapod::Spatial::RotationMatrixAboutX::m_c, and metapod::Spatial::RotationMatrixAboutX::m_s.
template<typename traits> RotationMatrix metapod::Spatial::RotationMatrixChangeAxis< traits >::operator* (const RotationMatrixAboutY & aRM) const [inline]
References metapod::Spatial::RotationMatrixAboutY::m_c, and metapod::Spatial::RotationMatrixAboutY::m_s.
template<typename traits> RotationMatrix metapod::Spatial::RotationMatrixChangeAxis< traits >::operator* (const RotationMatrixAboutZ & aRM) const [inline]
References metapod::Spatial::RotationMatrixAboutZ::m_c, and metapod::Spatial::RotationMatrixAboutZ::m_s.
template<typename traits> Vector3d metapod::Spatial::RotationMatrixChangeAxis< traits >::operator* (const Vector3d & ar) const [inline]
template<typename traits> RotationMatrixChangeAxis metapod::Spatial::RotationMatrixChangeAxis< traits >::operator- () const [inline]
template<typename traits> void metapod::Spatial::RotationMatrixChangeAxis< traits >::randomInit () [inline]
template<typename traits> Matrix3d metapod::Spatial::RotationMatrixChangeAxis< traits >::rotGeneralMatrix (const Matrix3d & A) const [inline]
template<typename traits> ltI metapod::Spatial::RotationMatrixChangeAxis< traits >::rotSymmetricMatrix (const ltI & A) [inline]
References metapod::Spatial::ltI::m_ltI.
Referenced by metapod::Spatial::RotationMatrixChangeAxis< traits >::rotTSymmetricMatrix().
template<typename traits> ltI metapod::Spatial::RotationMatrixChangeAxis< traits >::rotTSymmetricMatrix (const ltI & A) [inline]
References metapod::Spatial::RotationMatrixChangeAxis< traits >::rotSymmetricMatrix().
template<typename traits> Matrix3d metapod::Spatial::RotationMatrixChangeAxis< traits >::toMatrix () [inline]
Referenced by metapod::Spatial::RotationMatrixChangeAxis< traits >::operator*().
template<typename traits> RotationMatrixChangeAxis metapod::Spatial::RotationMatrixChangeAxis< traits >::transpose () const [inline]
Friends And Related Function Documentation
template<typename traits> Matrix3d operator* (const Matrix3d & A, const RotationMatrixChangeAxis< traits > & aRMCA) [friend]
template<typename traits> std::ostream& operator<< (std::ostream & os, const RotationMatrixChangeAxis< traits > & aRMCA) [friend]