metapod::Spatial::RotationMatrixIdentity Struct Reference
metapod::Spatial::RotationMatrixIdentity Struct Reference
#include <metapod/tools/spatial/rm-identity.hh>
Public Member Functions
RotationMatrixIdentity ()
RotationMatrixIdentity (const RotationMatrixIdentity &aR)
RotationMatrixIdentity (const FloatType &aR)
void randomInit ()
Random initialization.
Matrix3d toMatrix () const
Returns a 3x3 eigen matrix.
RotationMatrixIdentity transpose () const
Matrix3d operator* (const Matrix3d &A) const
RotationMatrixIdentity operator* (const RotationMatrixIdentity &arm) const
Computes the multiplication between rotation matrix.
Vector3d operator* (const Vector3d &A) const
Computes $f v = RM u $f with $ v,u {R}^3 $.
RotationMatrixIdentity operator* (FloatType a) const
RotationMatrixIdentity operator- () const
FloatType operator() (int x, int y) const
Vector3d col (int x) const
Matrix3d rotGeneralMatrix (const Matrix3d &A) const
Compute the $f EAE^{T}$f.
lowerTriangularMatrix rotTSymmetricMatrix (const lowerTriangularMatrix &A) const
Compute the rotation for a symmetric matrix.
lowerTriangularMatrix rotSymmetricMatrix (const lowerTriangularMatrix &A) const
Public Attributes
FloatType m_scalar
Friends
RotationMatrixIdentity operator* (FloatType a, RotationMatrixIdentity alti)
template<class T >
T operator* (const T &aT, RotationMatrixIdentity alti)
std::ostream & operator<< (std::ostream &os, const struct RotationMatrixIdentity &aRMAX)
Constructor & Destructor Documentation
metapod::Spatial::RotationMatrixIdentity::RotationMatrixIdentity () [inline]
References m_scalar.
Referenced by operator*(), operator-(), and transpose().
metapod::Spatial::RotationMatrixIdentity::RotationMatrixIdentity (const RotationMatrixIdentity & aR) [inline]
References m_scalar.
metapod::Spatial::RotationMatrixIdentity::RotationMatrixIdentity (const FloatType & aR) [inline]
References m_scalar.
Member Function Documentation
Vector3d metapod::Spatial::RotationMatrixIdentity::col (int x) const [inline]
FloatType metapod::Spatial::RotationMatrixIdentity::operator() (int x, int y) const [inline]
References m_scalar.
Matrix3d metapod::Spatial::RotationMatrixIdentity::operator* (const Matrix3d & A) const [inline]
RotationMatrixIdentity metapod::Spatial::RotationMatrixIdentity::operator* (const RotationMatrixIdentity & arm) const [inline]
Computes the multiplication between rotation matrix.
Vector3d metapod::Spatial::RotationMatrixIdentity::operator* (const Vector3d & A) const [inline]
Computes $f v = RM u $f with $ v,u {R}^3 $.
RotationMatrixIdentity metapod::Spatial::RotationMatrixIdentity::operator* (FloatType a) const [inline]
References RotationMatrixIdentity().
RotationMatrixIdentity metapod::Spatial::RotationMatrixIdentity::operator- () const [inline]
References m_scalar, and RotationMatrixIdentity().
void metapod::Spatial::RotationMatrixIdentity::randomInit () [inline]
Random initialization.
Matrix3d metapod::Spatial::RotationMatrixIdentity::rotGeneralMatrix (const Matrix3d & A) const [inline]
Compute the $f EAE^{T}$f.
lowerTriangularMatrix metapod::Spatial::RotationMatrixIdentity::rotSymmetricMatrix (const lowerTriangularMatrix & A) const [inline]
lowerTriangularMatrix metapod::Spatial::RotationMatrixIdentity::rotTSymmetricMatrix (const lowerTriangularMatrix & A) const [inline]
Compute the rotation for a symmetric matrix.
Matrix3d metapod::Spatial::RotationMatrixIdentity::toMatrix () const [inline]
Returns a 3x3 eigen matrix.
RotationMatrixIdentity metapod::Spatial::RotationMatrixIdentity::transpose () const [inline]
References m_scalar, and RotationMatrixIdentity().
Friends And Related Function Documentation
RotationMatrixIdentity operator* (FloatType a, RotationMatrixIdentity alti) [friend]
template<class T > T operator* (const T & aT, RotationMatrixIdentity alti) [friend]
std::ostream& operator<< (std::ostream & os, const struct RotationMatrixIdentity & aRMAX) [friend]
Member Data Documentation
FloatType metapod::Spatial::RotationMatrixIdentity::m_scalar
Referenced by operator()(), operator-(), RotationMatrixIdentity(), and transpose().