metapod::depth_first_traversal< Visitor, Robot > Struct Template Reference
metapod::depth_first_traversal< Visitor, Robot > Struct Template Reference
#include <metapod/tools/depth_first_traversal.hh>
Static Public Member Functions
static void run ()
template<typename Arg >
static void run (Arg &arg)
template<typename Arg0 , typename Arg1 >
static void run (Arg0 &arg0, Arg1 &arg1)
template<typename Arg0 , typename Arg1 , typename Arg2 >
static void run (Arg0 &arg0, Arg1 &arg1, Arg2 &arg2)
template<typename Arg0 , typename Arg1 , typename Arg2 , typename Arg3 >
static void run (Arg0 &arg0, Arg1 &arg1, Arg2 &arg2, Arg3 &arg3)
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot>
struct metapod::depth_first_traversal< Visitor, Robot >
Member Function Documentation
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot > static void metapod::depth_first_traversal< Visitor, Robot >::run () [inline, static]
Referenced by metapod::getTorques(), metapod::printConf(), metapod::printNuFwdDyn(), metapod::printState(), metapod::printTorques(), metapod::printTransforms(), and metapod::depth_first_traversal< Visitor, Robot >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot > template<typename Arg > static void metapod::depth_first_traversal< Visitor, Robot >::run (Arg & arg) [inline, static]
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot > template<typename Arg0 , typename Arg1 > static void metapod::depth_first_traversal< Visitor, Robot >::run (Arg0 & arg0, Arg1 & arg1) [inline, static]
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot > template<typename Arg0 , typename Arg1 , typename Arg2 > static void metapod::depth_first_traversal< Visitor, Robot >::run (Arg0 & arg0, Arg1 & arg1, Arg2 & arg2) [inline, static]
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot > template<typename Arg0 , typename Arg1 , typename Arg2 , typename Arg3 > static void metapod::depth_first_traversal< Visitor, Robot >::run (Arg0 & arg0, Arg1 & arg1, Arg2 & arg2, Arg3 & arg3) [inline, static]
References metapod::depth_first_traversal< Visitor, Robot >::run().