metapod::Spatial::Motion Class Reference
metapod::Spatial::Motion Class Reference
#include <metapod/tools/spatial/motion.hh>
Public Member Functions
Motion ()
Motion (const Vector3d &w, const Vector3d &v)
Motion (const Vector6d &v)
const Vector3d & w () const
const Vector3d & v () const
void w (const Vector3d &v)
void v (const Vector3d &v)
Motion & operator= (const Vector6d &v)
Motion operator- () const
Motion operator+ (const Motion &mv) const
Motion operator* (FloatType a) const
Motion operator^ (const Motion &mv) const
Force operator^ (const Force &fv) const
Static Public Member Functions
static const Motion Zero ()
Friends
Motion operator* (FloatType a, const Motion &mv)
std::ostream & operator<< (std::ostream &os, const Motion &mv)
Constructor & Destructor Documentation
metapod::Spatial::Motion::Motion () [inline]
Referenced by operator*(), operator+(), operator-(), operator^(), and Zero().
metapod::Spatial::Motion::Motion (const Vector3d & w, const Vector3d & v) [inline]
metapod::Spatial::Motion::Motion (const Vector6d & v) [inline]
Member Function Documentation
Motion metapod::Spatial::Motion::operator* (FloatType a) const [inline]
References Motion().
Motion metapod::Spatial::Motion::operator+ (const Motion & mv) const [inline]
References Motion(), v(), and w().
Motion metapod::Spatial::Motion::operator- () const [inline]
References Motion().
Motion& metapod::Spatial::Motion::operator= (const Vector6d & v) [inline]
Motion metapod::Spatial::Motion::operator^ (const Motion & mv) const [inline]
References Motion(), v(), and w().
Force metapod::Spatial::Motion::operator^ (const Force & fv) const [inline]
References metapod::Spatial::Force::f(), and metapod::Spatial::Force::n().
const Vector3d& metapod::Spatial::Motion::v () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::apply(), metapod::Spatial::TransformT< RotationClass >::applyInv(), metapod::Spatial::OperatorMul< T, U, S >::mul(), metapod::Spatial::TransformT< RotationClass >::operator*(), operator+(), operator^(), metapod::RevoluteAxisAnyJoint::RevoluteAxisAnyJoint(), metapod::RevoluteAxisXJoint::RevoluteAxisXJoint(), metapod::RevoluteAxisYJoint::RevoluteAxisYJoint(), metapod::RevoluteAxisZJoint::RevoluteAxisZJoint(), metapod::Spatial::sum(), and w().
void metapod::Spatial::Motion::v (const Vector3d & v) [inline]
References v().
Referenced by v().
const Vector3d& metapod::Spatial::Motion::w () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::apply(), metapod::Spatial::TransformT< RotationClass >::applyInv(), metapod::RevoluteAxisAnyJoint::jcalc(), metapod::RevoluteAxisYJoint::jcalc(), metapod::RevoluteAxisZJoint::jcalc(), metapod::RevoluteAxisXJoint::jcalc(), metapod::Spatial::OperatorMul< T, U, S >::mul(), metapod::Spatial::TransformT< RotationClass >::operator*(), operator+(), operator^(), and metapod::Spatial::sum().
void metapod::Spatial::Motion::w (const Vector3d & v) [inline]
References v().
static const Motion metapod::Spatial::Motion::Zero () [inline, static]
References Motion().
Friends And Related Function Documentation
Motion operator* (FloatType a, const Motion & mv) [friend]
std::ostream& operator<< (std::ostream & os, const Motion & mv) [friend]