metapod::Spatial::ConstraintMotionFreeFlyer Class Reference
metapod::Spatial::ConstraintMotionFreeFlyer Class Reference
#include <metapod/tools/spatial/cm-freeflyer.hh>
Public Member Functions
ConstraintMotionFreeFlyer ()
Matrix6d operator* (FloatType x) const
Vector6d operator* (const Eigen::Matrix< FloatType, 6, 1 > &ddqi) const
void setlocalR (const Matrix3d &localR)
const Matrix6d & S () const
Matrix6d transpose () const
Constructor & Destructor Documentation
metapod::Spatial::ConstraintMotionFreeFlyer::ConstraintMotionFreeFlyer () [inline]
Member Function Documentation
Matrix6d metapod::Spatial::ConstraintMotionFreeFlyer::operator* (FloatType x) const [inline]
Vector6d metapod::Spatial::ConstraintMotionFreeFlyer::operator* (const Eigen::Matrix< FloatType, 6, 1 > & ddqi) const [inline]
const Matrix6d& metapod::Spatial::ConstraintMotionFreeFlyer::S () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::apply(), metapod::FreeFlyerJoint::jcalc(), and metapod::Spatial::OperatorMul< T, U, S >::mul().
void metapod::Spatial::ConstraintMotionFreeFlyer::setlocalR (const Matrix3d & localR) [inline]
Referenced by metapod::FreeFlyerJoint::bcalc().
Matrix6d metapod::Spatial::ConstraintMotionFreeFlyer::transpose () const [inline]