metapod::Spatial::RotationMatrix Struct Reference
metapod::Spatial::RotationMatrix Struct Reference
#include <metapod/tools/spatial/rm-general.hh>
Public Member Functions
RotationMatrix ()
RotationMatrix (const Matrix3d &aR)
void randomInit ()
Random initialization.
const Matrix3d & toMatrix () const
Returns a 3x3 eigen matrix.
void setRotationMatrix (const Matrix3d &rm)
Set the rotation matrix.
void decompose (const Matrix3d &A, Matrix3_2d &L) const
Computes L for a general matrix A.
void decomposeltI (const struct ltI &A, Matrix3_2d &L) const
Computes L for a symmetric matrix A.
RotationMatrix transpose () const
Matrix3d operator* (const Matrix3d &A) const
RotationMatrix operator* (const RotationMatrix &arm) const
Computes the multiplication between rotation matrix.
Vector3d operator* (const Vector3d &A) const
Computes $f v = RM u $f with $ v,u {R}^3 $.
RotationMatrix operator* (FloatType a) const
RotationMatrix operator- () const
FloatType operator() (int x, int y) const
Vector3d col (int x) const
Matrix3d rotGeneralMatrix (const Matrix3d &A) const
Compute the $f EAE^{T}$f.
lowerTriangularMatrix rotTSymmetricMatrix (const lowerTriangularMatrix &A) const
Compute the rotation for a symmetric matrix.
lowerTriangularMatrix rotSymmetricMatrix (const lowerTriangularMatrix &A) const
Public Attributes
Matrix3d m_rm
Friends
RotationMatrix operator* (FloatType a, RotationMatrix alti)
std::ostream & operator<< (std::ostream &os, const struct RotationMatrix &aRMAX)
Constructor & Destructor Documentation
metapod::Spatial::RotationMatrix::RotationMatrix () [inline]
References m_rm.
Referenced by operator*(), operator-(), and transpose().
metapod::Spatial::RotationMatrix::RotationMatrix (const Matrix3d & aR) [inline]
References m_rm.
Member Function Documentation
Vector3d metapod::Spatial::RotationMatrix::col (int x) const [inline]
References m_rm.
void metapod::Spatial::RotationMatrix::decompose (const Matrix3d & A, Matrix3_2d & L) const [inline]
Computes L for a general matrix A.
Referenced by rotGeneralMatrix().
void metapod::Spatial::RotationMatrix::decomposeltI (const struct ltI & A, Matrix3_2d & L) const [inline]
Computes L for a symmetric matrix A.
References metapod::Spatial::ltI::m_ltI.
Referenced by rotSymmetricMatrix(), and rotTSymmetricMatrix().
FloatType metapod::Spatial::RotationMatrix::operator() (int x, int y) const [inline]
References m_rm.
Matrix3d metapod::Spatial::RotationMatrix::operator* (const Matrix3d & A) const [inline]
References m_rm.
RotationMatrix metapod::Spatial::RotationMatrix::operator* (const RotationMatrix & arm) const [inline]
Computes the multiplication between rotation matrix.
References m_rm.
Vector3d metapod::Spatial::RotationMatrix::operator* (const Vector3d & A) const [inline]
Computes $f v = RM u $f with $ v,u {R}^3 $.
References m_rm.
RotationMatrix metapod::Spatial::RotationMatrix::operator* (FloatType a) const [inline]
References m_rm, and RotationMatrix().
RotationMatrix metapod::Spatial::RotationMatrix::operator- () const [inline]
References m_rm, and RotationMatrix().
void metapod::Spatial::RotationMatrix::randomInit () [inline]
Random initialization.
References m_rm.
Matrix3d metapod::Spatial::RotationMatrix::rotGeneralMatrix (const Matrix3d & A) const [inline]
Compute the $f EAE^{T}$f.
References decompose(), and m_rm.
lowerTriangularMatrix metapod::Spatial::RotationMatrix::rotSymmetricMatrix (const lowerTriangularMatrix & A) const [inline]
References decomposeltI(), metapod::Spatial::ltI::m_ltI, and m_rm.
lowerTriangularMatrix metapod::Spatial::RotationMatrix::rotTSymmetricMatrix (const lowerTriangularMatrix & A) const [inline]
Compute the rotation for a symmetric matrix.
References decomposeltI(), metapod::Spatial::ltI::m_ltI, and m_rm.
void metapod::Spatial::RotationMatrix::setRotationMatrix (const Matrix3d & rm) [inline]
Set the rotation matrix.
References m_rm.
const Matrix3d& metapod::Spatial::RotationMatrix::toMatrix () const [inline]
Returns a 3x3 eigen matrix.
References m_rm.
Referenced by metapod::Spatial::RotationBinaryOp< RotationMatrixT, RotMatChgAxis >::operator*(), and metapod::Spatial::RotationBinaryOp< RotationMatrixT, RotMatChgAxis >::RotationBinaryOp().
RotationMatrix metapod::Spatial::RotationMatrix::transpose () const [inline]
References m_rm, and RotationMatrix().
Friends And Related Function Documentation
RotationMatrix operator* (FloatType a, RotationMatrix alti) [friend]
std::ostream& operator<< (std::ostream & os, const struct RotationMatrix & aRMAX) [friend]
Member Data Documentation
Matrix3d metapod::Spatial::RotationMatrix::m_rm
Referenced by col(), operator()(), operator*(), metapod::Spatial::RotationMatrixAboutZ::operator*(), metapod::Spatial::RotationMatrixAboutY::operator*(), metapod::Spatial::RotationMatrixAboutX::operator*(), metapod::Spatial::RotationMatrixChangeAxis< traits >::operator*(), operator-(), randomInit(), RotationMatrix(), rotGeneralMatrix(), rotSymmetricMatrix(), rotTSymmetricMatrix(), setRotationMatrix(), toMatrix(), and transpose().