metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id > Struct Template Reference
metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id > Struct Template Reference
#include <metapod/tools/depth_first_traversal.hh>
Public Types
typedef Nodes< Robot, node_id >
::type Node
Static Public Member Functions
static void run ()
template<typename Arg >
static void run (Arg &arg)
template<typename Arg0 , typename Arg1 >
static void run (Arg0 &arg0, Arg1 &arg1)
template<typename Arg0 , typename Arg1 , typename Arg2 >
static void run (Arg0 &arg0, Arg1 &arg1, Arg2 &arg2)
template<typename Arg0 , typename Arg1 , typename Arg2 , typename Arg3 >
static void run (Arg0 &arg0, Arg1 &arg1, Arg2 &arg2, Arg3 &arg3)
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot, int node_id>
struct metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >
Member Typedef Documentation
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id> typedef Nodes<Robot, node_id>::type metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::Node
Member Function Documentation
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id> static void metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run () [inline, static]
Referenced by metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id> template<typename Arg > static void metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run (Arg & arg) [inline, static]
References metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id> template<typename Arg0 , typename Arg1 > static void metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run (Arg0 & arg0, Arg1 & arg1) [inline, static]
References metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id> template<typename Arg0 , typename Arg1 , typename Arg2 > static void metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run (Arg0 & arg0, Arg1 & arg1, Arg2 & arg2) [inline, static]
References metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id> template<typename Arg0 , typename Arg1 , typename Arg2 , typename Arg3 > static void metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run (Arg0 & arg0, Arg1 & arg1, Arg2 & arg2, Arg3 & arg3) [inline, static]
References metapod::internal::depth_first_traversal_internal< Visitor, Robot, node_id >::run().