metapod::Spatial::OperatorMul< T, U, S > Class Template Reference
metapod::Spatial::OperatorMul< T, U, S > Class Template Reference
#include <metapod/tools/fwd.hh>
Public Member Functions
T mul (const U &u, const S &s) const
template<>
Vector6d mul (const Inertia &m, const ConstraintMotionAnyAxis &a) const
template<>
Matrix6d mul (const Inertia &m, const ConstraintMotionFreeFlyer &a) const
template<>
Inertia mul (const Inertia &m, const FloatType &a) const
template<>
Force mul (const Inertia &m, const Motion &mv) const
template<class T, class U, class S>
class metapod::Spatial::OperatorMul< T, U, S >
Member Function Documentation
template<> Vector6d metapod::Spatial::OperatorMul< Vector6d, Inertia, ConstraintMotionAnyAxis >::mul (const Inertia & m, const ConstraintMotionAnyAxis & a) const [inline]
References metapod::Spatial::ltI::m_ltI, metapod::Spatial::ConstraintMotionAnyAxis::S(), and metapod::Spatial::skew().
template<> Matrix6d metapod::Spatial::OperatorMul< Matrix6d, Inertia, ConstraintMotionFreeFlyer >::mul (const Inertia & m, const ConstraintMotionFreeFlyer & a) const [inline]
References metapod::Spatial::Inertia::h(), metapod::Spatial::Inertia::I(), metapod::Spatial::Inertia::m(), metapod::Spatial::ConstraintMotionFreeFlyer::S(), and metapod::Spatial::skew().
template<class T, class U, class S> T metapod::Spatial::OperatorMul< T, U, S >::mul (const U & u, const S & s) const
Referenced by metapod::Spatial::operator*().
template<> Inertia metapod::Spatial::OperatorMul< Inertia, Inertia, FloatType >::mul (const Inertia & m, const FloatType & a) const [inline]
template<> Force metapod::Spatial::OperatorMul< Force, Inertia, Motion >::mul (const Inertia & m, const Motion & mv) const [inline]
References metapod::Spatial::Motion::v(), and metapod::Spatial::Motion::w().