metapod::Spatial::InertiaTpl< FloatType > Class Template Reference
metapod::Spatial::InertiaTpl< FloatType > Class Template Reference
#include <metapod/tools/spatial/inertia.hh>
Public Member Functions
InertiaTpl ()
InertiaTpl (FloatType m, const Vector3d &h, const Matrix3d &I)
InertiaTpl (FloatType m, const Vector3d &h, const class ltI< FloatType > &I)
FloatType m () const
const Vector3d & h () const
const ltI< FloatType > & I () const
Matrix6d toMatrix () const
InertiaTpl operator+ (const InertiaTpl &other) const
InertiaTpl operator* (const FloatType &a) const
Force operator* (const Motion &mv) const
Static Public Member Functions
static const InertiaTpl Zero ()
template<class FloatType>
class metapod::Spatial::InertiaTpl< FloatType >
Constructor & Destructor Documentation
template<class FloatType> metapod::Spatial::InertiaTpl< FloatType >::InertiaTpl () [inline]
Referenced by metapod::Spatial::InertiaTpl< FloatType >::operator*(), metapod::Spatial::InertiaTpl< FloatType >::operator+(), and metapod::Spatial::InertiaTpl< FloatType >::Zero().
template<class FloatType> metapod::Spatial::InertiaTpl< FloatType >::InertiaTpl (FloatType m, const Vector3d & h, const Matrix3d & I) [inline]
template<class FloatType> metapod::Spatial::InertiaTpl< FloatType >::InertiaTpl (FloatType m, const Vector3d & h, const class ltI< FloatType > & I) [inline]
Member Function Documentation
template<class FloatType> const Vector3d& metapod::Spatial::InertiaTpl< FloatType >::h () const [inline]
template<class FloatType> const ltI<FloatType>& metapod::Spatial::InertiaTpl< FloatType >::I () const [inline]
template<class FloatType> FloatType metapod::Spatial::InertiaTpl< FloatType >::m () const [inline]
template<class FloatType> InertiaTpl metapod::Spatial::InertiaTpl< FloatType >::operator* (const FloatType & a) const [inline]
References metapod::Spatial::InertiaTpl< FloatType >::InertiaTpl().
template<class FloatType> Force metapod::Spatial::InertiaTpl< FloatType >::operator* (const Motion & mv) const [inline]
template<class FloatType> InertiaTpl metapod::Spatial::InertiaTpl< FloatType >::operator+ (const InertiaTpl< FloatType > & other) const [inline]
References metapod::Spatial::InertiaTpl< FloatType >::InertiaTpl().
template<class FloatType> Matrix6d metapod::Spatial::InertiaTpl< FloatType >::toMatrix () const [inline]
References metapod::Spatial::skew().
template<class FloatType> static const InertiaTpl metapod::Spatial::InertiaTpl< FloatType >::Zero () [inline, static]
References metapod::Spatial::InertiaTpl< FloatType >::InertiaTpl().