metapod::RevoluteAxisXJoint Class Reference
metapod::RevoluteAxisXJoint Class Reference
#include <metapod/tools/joint-aboutxaxis.hh>
Public Member Functions
RevoluteAxisXJoint ()
void bcalc (const Vector1d &qi)
void jcalc (const Vector1d &qi, const Vector1d &dqi)
Public Attributes
Spatial::TransformX Xj
Spatial::Motion cj
Spatial::Motion vj
Spatial::ConstraintMotionOneAxis
< Spatial::AxisX > S
Spatial::Force f
Vector1d torque
Static Public Attributes
static const int NBDOF = 1
Constructor & Destructor Documentation
metapod::RevoluteAxisXJoint::RevoluteAxisXJoint () [inline]
References metapod::Spatial::Motion::v(), and vj.
Member Function Documentation
void metapod::RevoluteAxisXJoint::bcalc (const Vector1d & qi) [inline]
References Xj.
Referenced by jcalc().
void metapod::RevoluteAxisXJoint::jcalc (const Vector1d & qi, const Vector1d & dqi) [inline]
References bcalc(), vj, and metapod::Spatial::Motion::w().
Member Data Documentation
Spatial::Motion metapod::RevoluteAxisXJoint::cj
Spatial::Force metapod::RevoluteAxisXJoint::f
const int metapod::RevoluteAxisXJoint::NBDOF = 1 [static]
Spatial::ConstraintMotionOneAxis<Spatial::AxisX> metapod::RevoluteAxisXJoint::S
Vector1d metapod::RevoluteAxisXJoint::torque
Spatial::Motion metapod::RevoluteAxisXJoint::vj
Referenced by jcalc(), and RevoluteAxisXJoint().
Spatial::TransformX metapod::RevoluteAxisXJoint::Xj
Referenced by bcalc().