metapod::Spatial::Force Class Reference
metapod::Spatial::Force Class Reference
#include <metapod/tools/spatial/force.hh>
Public Member Functions
Force ()
Force (const Vector3d &n, const Vector3d &f)
Force (const Vector6d &v)
const Vector3d & n () const
const Vector3d & f () const
Vector6d toVector () const
Force & operator= (const Vector6d &v)
Force operator+ (const Force &fv) const
Force operator- () const
Force operator- (const Force &fv) const
Force operator* (FloatType a) const
Static Public Member Functions
static const Force Zero ()
Friends
Force operator* (FloatType a, const Force &fv)
std::ostream & operator<< (std::ostream &os, const Force &fv)
Constructor & Destructor Documentation
metapod::Spatial::Force::Force () [inline]
Referenced by operator*(), operator+(), operator-(), and Zero().
metapod::Spatial::Force::Force (const Vector3d & n, const Vector3d & f) [inline]
metapod::Spatial::Force::Force (const Vector6d & v) [inline]
Member Function Documentation
const Vector3d& metapod::Spatial::Force::f () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::apply(), metapod::Spatial::TransformT< RotationClass >::applyInv(), metapod::Spatial::TransformT< RotationClass >::operator*(), operator+(), operator-(), metapod::Spatial::Motion::operator^(), and metapod::Spatial::sum().
const Vector3d& metapod::Spatial::Force::n () const [inline]
Referenced by metapod::Spatial::TransformT< RotationClass >::apply(), metapod::Spatial::TransformT< RotationClass >::applyInv(), metapod::Spatial::TransformT< RotationClass >::operator*(), operator+(), operator-(), metapod::Spatial::Motion::operator^(), and metapod::Spatial::sum().
Force metapod::Spatial::Force::operator* (FloatType a) const [inline]
References Force().
Force metapod::Spatial::Force::operator+ (const Force & fv) const [inline]
References f(), Force(), and n().
Force metapod::Spatial::Force::operator- () const [inline]
References Force().
Force metapod::Spatial::Force::operator- (const Force & fv) const [inline]
References f(), Force(), and n().
Force& metapod::Spatial::Force::operator= (const Vector6d & v) [inline]
Vector6d metapod::Spatial::Force::toVector () const [inline]
static const Force metapod::Spatial::Force::Zero () [inline, static]
References Force().
Friends And Related Function Documentation
Force operator* (FloatType a, const Force & fv) [friend]
std::ostream& operator<< (std::ostream & os, const Force & fv) [friend]