metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id > Struct Template Reference
metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id > Struct Template Reference
#include <metapod/tools/backward_traversal_prev.hh>
Public Types
typedef Nodes< Robot,
start_node_id >::type StartNode
Public Member Functions
METAPOD_STATIC_ASSERT ((is_ancestor< Robot, end_node_id, start_node_id >::value),"end node should be an ancestor if start node")
Static Public Member Functions
static void run ()
template<typename Arg0 >
static void run (Arg0 &arg0)
template<typename Arg0 , typename Arg1 >
static void run (Arg0 &arg0, Arg1 &arg1)
template<template< typename AnyRobot, int any_node_id, int any_prev_node_id > class Visitor, typename Robot, int start_node_id, int end_node_id = NO_PARENT>
struct metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id >
Member Typedef Documentation
template<template< typename AnyRobot, int any_node_id, int any_prev_node_id > class Visitor, typename Robot , int start_node_id, int end_node_id = NO_PARENT> typedef Nodes<Robot, start_node_id>::type metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id >::StartNode
Member Function Documentation
template<template< typename AnyRobot, int any_node_id, int any_prev_node_id > class Visitor, typename Robot , int start_node_id, int end_node_id = NO_PARENT> metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id >::METAPOD_STATIC_ASSERT ((is_ancestor< Robot, end_node_id, start_node_id >::value) , "end node should be an ancestor if start node")
template<template< typename AnyRobot, int any_node_id, int any_prev_node_id > class Visitor, typename Robot , int start_node_id, int end_node_id = NO_PARENT> static void metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id >::run () [inline, static]
Referenced by metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id >::run().
template<template< typename AnyRobot, int any_node_id, int any_prev_node_id > class Visitor, typename Robot , int start_node_id, int end_node_id = NO_PARENT> template<typename Arg0 > static void metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id >::run (Arg0 & arg0) [inline, static]
References metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id >::run().
template<template< typename AnyRobot, int any_node_id, int any_prev_node_id > class Visitor, typename Robot , int start_node_id, int end_node_id = NO_PARENT> template<typename Arg0 , typename Arg1 > static void metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id >::run (Arg0 & arg0, Arg1 & arg1) [inline, static]
References metapod::backward_traversal_prev< Visitor, Robot, start_node_id, end_node_id >::run().