metapod::Spatial::ForceTpl< FloatType > Class Template Reference
metapod::Spatial::ForceTpl< FloatType > Class Template Reference
#include <metapod/tools/spatial/force.hh>
Public Member Functions
ForceTpl ()
ForceTpl (const Vector3d &n, const Vector3d &f)
ForceTpl (const Vector6d &v)
const Vector3d & n () const
const Vector3d & f () const
Vector6d toVector () const
ForceTpl & operator= (const Vector6d &v)
ForceTpl operator+ (const ForceTpl &fv) const
ForceTpl operator- () const
ForceTpl operator- (const ForceTpl &fv) const
ForceTpl operator* (FloatType a) const
Static Public Member Functions
static const ForceTpl Zero ()
Friends
ForceTpl operator* (FloatType a, const ForceTpl &fv)
std::ostream & operator<< (std::ostream &os, const ForceTpl &fv)
template<class FloatType>
class metapod::Spatial::ForceTpl< FloatType >
Constructor & Destructor Documentation
template<class FloatType> metapod::Spatial::ForceTpl< FloatType >::ForceTpl () [inline]
Referenced by metapod::Spatial::ForceTpl< FloatType >::operator*(), metapod::Spatial::ForceTpl< FloatType >::operator+(), metapod::Spatial::ForceTpl< FloatType >::operator-(), and metapod::Spatial::ForceTpl< FloatType >::Zero().
template<class FloatType> metapod::Spatial::ForceTpl< FloatType >::ForceTpl (const Vector3d & n, const Vector3d & f) [inline]
template<class FloatType> metapod::Spatial::ForceTpl< FloatType >::ForceTpl (const Vector6d & v) [inline]
Member Function Documentation
template<class FloatType> const Vector3d& metapod::Spatial::ForceTpl< FloatType >::f () const [inline]
Referenced by metapod::Spatial::ForceTpl< FloatType >::operator+(), metapod::Spatial::ForceTpl< FloatType >::operator-(), and metapod::Spatial::sum().
template<class FloatType> const Vector3d& metapod::Spatial::ForceTpl< FloatType >::n () const [inline]
Referenced by metapod::Spatial::ForceTpl< FloatType >::operator+(), metapod::Spatial::ForceTpl< FloatType >::operator-(), and metapod::Spatial::sum().
template<class FloatType> ForceTpl metapod::Spatial::ForceTpl< FloatType >::operator* (FloatType a) const [inline]
References metapod::Spatial::ForceTpl< FloatType >::ForceTpl().
template<class FloatType> ForceTpl metapod::Spatial::ForceTpl< FloatType >::operator+ (const ForceTpl< FloatType > & fv) const [inline]
References metapod::Spatial::ForceTpl< FloatType >::f(), metapod::Spatial::ForceTpl< FloatType >::ForceTpl(), and metapod::Spatial::ForceTpl< FloatType >::n().
template<class FloatType> ForceTpl metapod::Spatial::ForceTpl< FloatType >::operator- () const [inline]
References metapod::Spatial::ForceTpl< FloatType >::ForceTpl().
template<class FloatType> ForceTpl metapod::Spatial::ForceTpl< FloatType >::operator- (const ForceTpl< FloatType > & fv) const [inline]
References metapod::Spatial::ForceTpl< FloatType >::f(), metapod::Spatial::ForceTpl< FloatType >::ForceTpl(), and metapod::Spatial::ForceTpl< FloatType >::n().
template<class FloatType> ForceTpl& metapod::Spatial::ForceTpl< FloatType >::operator= (const Vector6d & v) [inline]
template<class FloatType> Vector6d metapod::Spatial::ForceTpl< FloatType >::toVector () const [inline]
template<class FloatType> static const ForceTpl metapod::Spatial::ForceTpl< FloatType >::Zero () [inline, static]
References metapod::Spatial::ForceTpl< FloatType >::ForceTpl().
Friends And Related Function Documentation
template<class FloatType> ForceTpl operator* (FloatType a, const ForceTpl< FloatType > & fv) [friend]
template<class FloatType> std::ostream& operator<< (std::ostream & os, const ForceTpl< FloatType > & fv) [friend]