metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id > Struct Template Reference
metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id > Struct Template Reference
#include <metapod/tools/backward_traversal.hh>
Public Types
typedef Nodes< Robot, node_id >
::type Node
Static Public Member Functions
static void run ()
template<typename Arg0 >
static void run (Arg0 &arg0)
template<typename Arg0 , typename Arg1 >
static void run (Arg0 &arg0, Arg1 &arg1)
template<typename Arg0 , typename Arg1 , typename Arg2 >
static void run (Arg0 &arg0, Arg1 &arg1, Arg2 &arg2)
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot, int node_id, int end_node_id>
struct metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >
Member Typedef Documentation
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id, int end_node_id> typedef Nodes<Robot, node_id>::type metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >::Node
Member Function Documentation
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id, int end_node_id> static void metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >::run () [inline, static]
Referenced by metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id, int end_node_id> template<typename Arg0 > static void metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >::run (Arg0 & arg0) [inline, static]
References metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id, int end_node_id> template<typename Arg0 , typename Arg1 > static void metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >::run (Arg0 & arg0, Arg1 & arg1) [inline, static]
References metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >::run().
template<template< typename AnyRobot, int any_node_id > class Visitor, typename Robot , int node_id, int end_node_id> template<typename Arg0 , typename Arg1 , typename Arg2 > static void metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >::run (Arg0 & arg0, Arg1 & arg1, Arg2 & arg2) [inline, static]
References metapod::internal::backward_traversal_internal< Visitor, Robot, node_id, end_node_id >::run().