metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits > Class Template Reference
metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits > Class Template Reference
Rotation matrix as axis permutation matrix.
#include <metapod/tools/spatial/rm-chgaxis.hh>
Public Types
typedef traits Traits
Public Member Functions
RotationMatrixChangeAxisTpl ()
RotationMatrixChangeAxisTpl (const RotationMatrixChangeAxisTpl &)
RotationMatrixChangeAxisTpl transpose () const
Matrix3d toMatrix ()
Matrix3d operator* (FloatType a) const
void randomInit ()
RotationMatrixChangeAxisTpl operator- () const
Matrix3d operator* (const Matrix3d &A) const
template<typename traits_rhs >
RotationMatrixChangeAxisTpl
< FloatType, rmca_traits_mul
< traits, traits_rhs > > operator* (const RotationMatrixChangeAxisTpl< FloatType, traits_rhs > &)
RotationMatrix operator* (const RotationMatrix &aRM) const
RotationMatrix operator* (const RotationMatrixAboutX &aRM) const
RotationMatrix operator* (const RotationMatrixAboutY &aRM) const
RotationMatrix operator* (const RotationMatrixAboutZ &aRM) const
Matrix3d rotGeneralMatrix (const Matrix3d &A) const
ltI< FloatType > rotSymmetricMatrix (const ltI< FloatType > &A)
ltI< FloatType > rotTSymmetricMatrix (const ltI< FloatType > &A)
Vector3d operator* (const Vector3d &ar) const
Friends
Matrix3d operator* (const Matrix3d &A, const RotationMatrixChangeAxisTpl< FloatType, traits > &aRMCA)
std::ostream & operator<< (std::ostream &os, const RotationMatrixChangeAxisTpl< FloatType, traits > &aRMCA)
Detailed Description
template<typename FloatType, typename traits>
class metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >
Rotation matrix as axis permutation matrix.
This matrix is defined by 7 parameters: .
Member Typedef Documentation
template<typename FloatType, typename traits> typedef traits metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::Traits
Constructor & Destructor Documentation
template<typename FloatType, typename traits> metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::RotationMatrixChangeAxisTpl () [inline]
template<typename FloatType, typename traits> metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::RotationMatrixChangeAxisTpl (const RotationMatrixChangeAxisTpl< FloatType, traits > &) [inline]
Member Function Documentation
template<typename FloatType, typename traits> Matrix3d metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator* (FloatType a) const [inline]
References metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::toMatrix().
template<typename FloatType, typename traits> Matrix3d metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator* (const Matrix3d & A) const [inline]
template<typename FloatType, typename traits> template<typename traits_rhs > RotationMatrixChangeAxisTpl< FloatType, rmca_traits_mul<traits,traits_rhs> > metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator* (const RotationMatrixChangeAxisTpl< FloatType, traits_rhs > &) [inline]
template<typename FloatType, typename traits> RotationMatrix metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator* (const RotationMatrix & aRM) const [inline]
template<typename FloatType, typename traits> RotationMatrix metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator* (const RotationMatrixAboutX & aRM) const [inline]
template<typename FloatType, typename traits> RotationMatrix metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator* (const RotationMatrixAboutY & aRM) const [inline]
template<typename FloatType, typename traits> RotationMatrix metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator* (const RotationMatrixAboutZ & aRM) const [inline]
template<typename FloatType, typename traits> Vector3d metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator* (const Vector3d & ar) const [inline]
template<typename FloatType, typename traits> RotationMatrixChangeAxisTpl metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator- () const [inline]
template<typename FloatType, typename traits> void metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::randomInit () [inline]
template<typename FloatType, typename traits> Matrix3d metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::rotGeneralMatrix (const Matrix3d & A) const [inline]
template<typename FloatType, typename traits> ltI<FloatType> metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::rotSymmetricMatrix (const ltI< FloatType > & A) [inline]
References metapod::Spatial::ltI< FloatType >::m_ltI.
Referenced by metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::rotTSymmetricMatrix().
template<typename FloatType, typename traits> ltI<FloatType> metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::rotTSymmetricMatrix (const ltI< FloatType > & A) [inline]
References metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::rotSymmetricMatrix().
template<typename FloatType, typename traits> Matrix3d metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::toMatrix () [inline]
Referenced by metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::operator*().
template<typename FloatType, typename traits> RotationMatrixChangeAxisTpl metapod::Spatial::RotationMatrixChangeAxisTpl< FloatType, traits >::transpose () const [inline]
Friends And Related Function Documentation
template<typename FloatType, typename traits> Matrix3d operator* (const Matrix3d & A, const RotationMatrixChangeAxisTpl< FloatType, traits > & aRMCA) [friend]
template<typename FloatType, typename traits> std::ostream& operator<< (std::ostream & os, const RotationMatrixChangeAxisTpl< FloatType, traits > & aRMCA) [friend]