metapod Namespace Reference
metapod Namespace Reference
Compute the kinematic jacobian.
Namespaces
namespace internal
namespace Spatial
Classes
struct crba
struct crba< Robot, false >
struct crba< Robot, true >
struct jac
struct jac_point_chain
Point in Chain Articular Jacobian Algorithm.
struct jac_point_relative
struct rnea
Templated Recursive Newton-Euler Algorithm.
struct rnea< Robot, false >
struct rnea< Robot, true >
struct backward_traversal
struct backward_traversal< Visitor, Robot, end_node_id, end_node_id >
struct backward_traversal_previous
struct backward_traversal_prev
struct backward_traversal_prev< Visitor, Robot, end_node_id, end_node_id >
struct bcalc
class Body
struct Nodes
struct deepest_common_ancestor
Deepest common ancestor node of two nodes A and B. The member.
struct depth_first_traversal
struct is_NO_PARENT
value member variable is true if Node is NP (no parent), and false otherwise.
struct is_NO_PARENT< Robot, NO_PARENT >
struct has_parent
value member variable is false if Node has no parent.
struct initConf
init a configuration vector with values from text file, formatted as printed by the printConf routine.
struct is_ancestor
value member variable is true if NodeA is an ancestor of NodeB, false otherwise.
struct is_ancestor< Robot, node_a_id, node_a_id >
struct is_ancestor< Robot, node_a_id, NO_PARENT >
struct is_ancestor< Robot, NO_PARENT, NO_PARENT >
struct jac_point_robot
struct jcalc
class RevoluteAxisXJoint
class RevoluteAxisYJoint
class RevoluteAxisZJoint
class RevoluteAxisAnyJoint
class FreeFlyerJoint
Typedefs
typedef double FloatType
typedef Eigen::Matrix
< FloatType, 1, 1 > Vector1d
typedef Eigen::Matrix
< FloatType, 3, 1 > Vector3d
typedef Eigen::Matrix
< FloatType, 6, 1 > Vector6d
typedef Eigen::Matrix
< FloatType, 1, 6 > Vector6dt
typedef Eigen::Matrix
< FloatType, 2, 2 > Matrix2d
typedef Eigen::Matrix
< FloatType, 3, 2 > Matrix3_2d
typedef Eigen::Matrix
< FloatType, 3, 3 > Matrix3d
typedef Eigen::Matrix
< FloatType, 6, 6 > Matrix6d
typedef Eigen::Matrix
< FloatType, Eigen::Dynamic,
Eigen::Dynamic > MatrixN
typedef Eigen::Matrix
< FloatType, Eigen::Dynamic, 1 > VectorN
typedef Eigen::AngleAxis
< FloatType > AngleAxisd
Functions
const Matrix3d matrix3dMaker (FloatType m00, FloatType m01, FloatType m02, FloatType m10, FloatType m11, FloatType m12, FloatType m20, FloatType m21, FloatType m22)
const Vector6d vector6dMaker (FloatType v0, FloatType v1, FloatType v2, FloatType v3, FloatType v4, FloatType v5)
Spatial::Motion set_gravity ()
Matrix3d Skew (const Vector3d &v)
Spatial::Inertia spatialInertiaMaker (const FloatType m, const Vector3d &CoM, const Matrix3d &inertia)
template<typename Robot >
void printState (const Robot &robot, std::ostream &os)
template<typename Robot >
void printConf (const VectorN &q, std::ostream &os)
template<typename Robot >
void printTransforms (const Robot &robot, std::ostream &os)
template<typename Robot >
void printTorques (Robot &robot, std::ostream &os)
template<typename Robot >
void getTorques (Robot &robot, typename Robot::confVector &v)
Variables
static const Spatial::Motion minus_g = set_gravity()
static const int MAX_NB_JOINTS = 50
static const int MAX_NB_CHILDREN_PER_NODE = 5
static const int NO_PARENT = -1
static const int NO_CHILD = -2
static const int NO_NODE = -3
Detailed Description
Compute the kinematic jacobian.
Implementation of an algorithm that checks whether a node is an ancestor of another one or not.
Implementation of two algorithms that check whether a node is NP (no parent) or not and if it has a parent or not.
Implementation of an algorithm that computes the deepest common ancestor of two nodes.
Implementation of articular jacobian of point given an influencing chain of joints.
i.e. the matrix J such that J*dq is the vertical concatenation of each body spatial motion vector (in the moving body frame)
Typedef Documentation
typedef Eigen::AngleAxis< FloatType > metapod::AngleAxisd
typedef double metapod::FloatType
typedef Eigen::Matrix< FloatType, 2, 2 > metapod::Matrix2d
typedef Eigen::Matrix< FloatType, 3, 2 > metapod::Matrix3_2d
typedef Eigen::Matrix< FloatType, 3, 3 > metapod::Matrix3d
typedef Eigen::Matrix< FloatType, 6, 6 > metapod::Matrix6d
typedef Eigen::Matrix< FloatType, Eigen::Dynamic, Eigen::Dynamic > metapod::MatrixN
typedef Eigen::Matrix< FloatType, 1, 1 > metapod::Vector1d
typedef Eigen::Matrix< FloatType, 3, 1 > metapod::Vector3d
typedef Eigen::Matrix< FloatType, 6, 1 > metapod::Vector6d
typedef Eigen::Matrix< FloatType, 1, 6 > metapod::Vector6dt
typedef Eigen::Matrix< FloatType, Eigen::Dynamic, 1 > metapod::VectorN
Function Documentation
template<typename Robot > void metapod::getTorques (Robot & robot, typename Robot::confVector & v)
References metapod::depth_first_traversal< Visitor, Robot >::run().
const Matrix3d metapod::matrix3dMaker (FloatType m00, FloatType m01, FloatType m02, FloatType m10, FloatType m11, FloatType m12, FloatType m20, FloatType m21, FloatType m22) [inline]
template<typename Robot > void metapod::printConf (const VectorN & q, std::ostream & os)
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<typename Robot > void metapod::printState (const Robot & robot, std::ostream & os)
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<typename Robot > void metapod::printTorques (Robot & robot, std::ostream & os)
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<typename Robot > void metapod::printTransforms (const Robot & robot, std::ostream & os)
References metapod::depth_first_traversal< Visitor, Robot >::run().
Spatial::Motion metapod::set_gravity () [inline]
Matrix3d metapod::Skew (const Vector3d & v) [inline]
Referenced by spatialInertiaMaker().
Spatial::Inertia metapod::spatialInertiaMaker (const FloatType m, const Vector3d & CoM, const Matrix3d & inertia) [inline]
References Skew().
const Vector6d metapod::vector6dMaker (FloatType v0, FloatType v1, FloatType v2, FloatType v3, FloatType v4, FloatType v5) [inline]
Variable Documentation
const int metapod::MAX_NB_CHILDREN_PER_NODE = 5 [static]
const int metapod::MAX_NB_JOINTS = 50 [static]
const Spatial::Motion metapod::minus_g = set_gravity() [static]
Referenced by metapod::rnea< Robot, false >::update_kinematics< node_id, NO_PARENT >::run().
const int metapod::NO_CHILD = -2 [static]
const int metapod::NO_NODE = -3 [static]
const int metapod::NO_PARENT = -1 [static]