metapod::Spatial::RotationMatrixIdentityTpl< FloatType > Struct Template Reference
metapod::Spatial::RotationMatrixIdentityTpl< FloatType > Struct Template Reference
#include <metapod/tools/spatial/rm-identity.hh>
Public Member Functions
RotationMatrixIdentityTpl ()
RotationMatrixIdentityTpl (const RotationMatrixIdentityTpl< FloatType > &aR)
RotationMatrixIdentityTpl (const FloatType &aR)
void randomInit ()
Random initialization.
Matrix3d toMatrix () const
Returns a 3x3 eigen matrix.
RotationMatrixIdentityTpl transpose () const
Matrix3d operator* (const Matrix3d &A) const
RotationMatrixIdentityTpl operator* (const RotationMatrixIdentityTpl &arm) const
Computes the multiplication between rotation matrix.
Vector3d operator* (const Vector3d &A) const
Computes $f v = RM u $f with $ v,u {R}^3 $.
RotationMatrixIdentityTpl operator* (FloatType a) const
RotationMatrixIdentityTpl operator- () const
FloatType operator() (int x, int y) const
Vector3d col (int x) const
Matrix3d rotGeneralMatrix (const Matrix3d &A) const
Compute the $f EAE^{T}$f.
ltI< FloatType > rotTSymmetricMatrix (const ltI< FloatType > &A) const
Compute the rotation for a symmetric matrix.
ltI< FloatType > rotSymmetricMatrix (const ltI< FloatType > &A) const
Public Attributes
EIGEN_METAPOD_TYPEDEFS
FloatType m_scalar
Friends
RotationMatrixIdentityTpl operator* (FloatType a, RotationMatrixIdentityTpl alti)
template<typename T >
T operator* (const T &aT, RotationMatrixIdentityTpl alti)
std::ostream & operator<< (std::ostream &os, const struct RotationMatrixIdentityTpl &aRMAX)
template<class FloatType>
struct metapod::Spatial::RotationMatrixIdentityTpl< FloatType >
Constructor & Destructor Documentation
template<class FloatType> metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::RotationMatrixIdentityTpl () [inline]
References metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::m_scalar.
Referenced by metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator*(), metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator-(), and metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::transpose().
template<class FloatType> metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::RotationMatrixIdentityTpl (const RotationMatrixIdentityTpl< FloatType > & aR) [inline]
References metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::m_scalar.
template<class FloatType> metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::RotationMatrixIdentityTpl (const FloatType & aR) [inline]
References metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::m_scalar.
Member Function Documentation
template<class FloatType> Vector3d metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::col (int x) const [inline]
template<class FloatType> FloatType metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator() (int x, int y) const [inline]
References metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::m_scalar.
template<class FloatType> Matrix3d metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator* (const Matrix3d & A) const [inline]
template<class FloatType> RotationMatrixIdentityTpl metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator* (const RotationMatrixIdentityTpl< FloatType > & arm) const [inline]
Computes the multiplication between rotation matrix.
template<class FloatType> Vector3d metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator* (const Vector3d & A) const [inline]
Computes $f v = RM u $f with $ v,u {R}^3 $.
template<class FloatType> RotationMatrixIdentityTpl metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator* (FloatType a) const [inline]
References metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::RotationMatrixIdentityTpl().
template<class FloatType> RotationMatrixIdentityTpl metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator- () const [inline]
References metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::m_scalar, and metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::RotationMatrixIdentityTpl().
template<class FloatType> void metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::randomInit () [inline]
Random initialization.
template<class FloatType> Matrix3d metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::rotGeneralMatrix (const Matrix3d & A) const [inline]
Compute the $f EAE^{T}$f.
template<class FloatType> ltI<FloatType> metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::rotSymmetricMatrix (const ltI< FloatType > & A) const [inline]
template<class FloatType> ltI<FloatType> metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::rotTSymmetricMatrix (const ltI< FloatType > & A) const [inline]
Compute the rotation for a symmetric matrix.
template<class FloatType> Matrix3d metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::toMatrix () const [inline]
Returns a 3x3 eigen matrix.
template<class FloatType> RotationMatrixIdentityTpl metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::transpose () const [inline]
References metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::m_scalar, and metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::RotationMatrixIdentityTpl().
Friends And Related Function Documentation
template<class FloatType> RotationMatrixIdentityTpl operator* (FloatType a, RotationMatrixIdentityTpl< FloatType > alti) [friend]
template<class FloatType> template<typename T > T operator* (const T & aT, RotationMatrixIdentityTpl< FloatType > alti) [friend]
template<class FloatType> std::ostream& operator<< (std::ostream & os, const struct RotationMatrixIdentityTpl< FloatType > & aRMAX) [friend]
Member Data Documentation
template<class FloatType> metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::EIGEN_METAPOD_TYPEDEFS
template<class FloatType> FloatType metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::m_scalar
Referenced by metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator()(), metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::operator-(), metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::RotationMatrixIdentityTpl(), and metapod::Spatial::RotationMatrixIdentityTpl< FloatType >::transpose().