metapod::Spatial::RotationMatrixTpl< FloatType > Struct Template Reference
metapod::Spatial::RotationMatrixTpl< FloatType > Struct Template Reference
#include <metapod/tools/spatial/rm-general.hh>
Public Member Functions
RotationMatrixTpl ()
RotationMatrixTpl (const Matrix3d &aR)
void randomInit ()
Random initialization.
const Matrix3d & toMatrix () const
Returns a 3x3 eigen matrix.
void setRotationMatrix (const Matrix3d &rm)
Set the rotation matrix.
void decompose (const Matrix3d &A, Matrix3_2d &L) const
Computes L for a general matrix A.
void decomposeltI (const class ltI< FloatType > &A, Matrix3_2d &L) const
Computes L for a symmetric matrix A.
RotationMatrixTpl transpose () const
Matrix3d operator* (const Matrix3d &A) const
RotationMatrixTpl operator* (const RotationMatrixTpl &arm) const
Computes the multiplication between rotation matrix.
Vector3d operator* (const Vector3d &A) const
Computes $f v = RM u $f with $ v,u {R}^3 $.
RotationMatrixTpl operator* (FloatType a) const
RotationMatrixTpl operator- () const
FloatType operator() (int x, int y) const
Vector3d col (int x) const
Matrix3d rotGeneralMatrix (const Matrix3d &A) const
Compute the $f EAE^{T}$f.
ltI< FloatType > rotTSymmetricMatrix (const ltI< FloatType > &A) const
Compute the rotation for a symmetric matrix.
ltI< FloatType > rotSymmetricMatrix (const ltI< FloatType > &A) const
Public Attributes
EIGEN_METAPOD_TYPEDEFS
Matrix3d m_rm
Friends
RotationMatrixTpl operator* (FloatType a, RotationMatrixTpl alti)
std::ostream & operator<< (std::ostream &os, const struct RotationMatrixTpl &aRMAX)
template<class FloatType>
struct metapod::Spatial::RotationMatrixTpl< FloatType >
Constructor & Destructor Documentation
template<class FloatType > metapod::Spatial::RotationMatrixTpl< FloatType >::RotationMatrixTpl () [inline]
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
Referenced by metapod::Spatial::RotationMatrixTpl< FloatType >::operator*(), metapod::Spatial::RotationMatrixTpl< FloatType >::operator-(), and metapod::Spatial::RotationMatrixTpl< FloatType >::transpose().
template<class FloatType > metapod::Spatial::RotationMatrixTpl< FloatType >::RotationMatrixTpl (const Matrix3d & aR) [inline]
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
Member Function Documentation
template<class FloatType > Vector3d metapod::Spatial::RotationMatrixTpl< FloatType >::col (int x) const [inline]
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > void metapod::Spatial::RotationMatrixTpl< FloatType >::decompose (const Matrix3d & A, Matrix3_2d & L) const [inline]
Computes L for a general matrix A.
Referenced by metapod::Spatial::RotationMatrixTpl< FloatType >::rotGeneralMatrix().
template<class FloatType > void metapod::Spatial::RotationMatrixTpl< FloatType >::decomposeltI (const class ltI< FloatType > & A, Matrix3_2d & L) const [inline]
Computes L for a symmetric matrix A.
References metapod::Spatial::ltI< FloatType >::m_ltI.
Referenced by metapod::Spatial::RotationMatrixTpl< FloatType >::rotSymmetricMatrix(), and metapod::Spatial::RotationMatrixTpl< FloatType >::rotTSymmetricMatrix().
template<class FloatType > FloatType metapod::Spatial::RotationMatrixTpl< FloatType >::operator() (int x, int y) const [inline]
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > Matrix3d metapod::Spatial::RotationMatrixTpl< FloatType >::operator* (const Matrix3d & A) const [inline]
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > RotationMatrixTpl metapod::Spatial::RotationMatrixTpl< FloatType >::operator* (const RotationMatrixTpl< FloatType > & arm) const [inline]
Computes the multiplication between rotation matrix.
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > Vector3d metapod::Spatial::RotationMatrixTpl< FloatType >::operator* (const Vector3d & A) const [inline]
Computes $f v = RM u $f with $ v,u {R}^3 $.
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > RotationMatrixTpl metapod::Spatial::RotationMatrixTpl< FloatType >::operator* (FloatType a) const [inline]
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm, and metapod::Spatial::RotationMatrixTpl< FloatType >::RotationMatrixTpl().
template<class FloatType > RotationMatrixTpl metapod::Spatial::RotationMatrixTpl< FloatType >::operator- () const [inline]
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm, and metapod::Spatial::RotationMatrixTpl< FloatType >::RotationMatrixTpl().
template<class FloatType > void metapod::Spatial::RotationMatrixTpl< FloatType >::randomInit () [inline]
Random initialization.
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > Matrix3d metapod::Spatial::RotationMatrixTpl< FloatType >::rotGeneralMatrix (const Matrix3d & A) const [inline]
Compute the $f EAE^{T}$f.
References metapod::Spatial::RotationMatrixTpl< FloatType >::decompose(), and metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > ltI<FloatType> metapod::Spatial::RotationMatrixTpl< FloatType >::rotSymmetricMatrix (const ltI< FloatType > & A) const [inline]
References metapod::Spatial::RotationMatrixTpl< FloatType >::decomposeltI(), metapod::Spatial::ltI< FloatType >::m_ltI, and metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > ltI<FloatType> metapod::Spatial::RotationMatrixTpl< FloatType >::rotTSymmetricMatrix (const ltI< FloatType > & A) const [inline]
Compute the rotation for a symmetric matrix.
References metapod::Spatial::RotationMatrixTpl< FloatType >::decomposeltI(), metapod::Spatial::ltI< FloatType >::m_ltI, and metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > void metapod::Spatial::RotationMatrixTpl< FloatType >::setRotationMatrix (const Matrix3d & rm) [inline]
Set the rotation matrix.
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > const Matrix3d& metapod::Spatial::RotationMatrixTpl< FloatType >::toMatrix () const [inline]
Returns a 3x3 eigen matrix.
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm.
template<class FloatType > RotationMatrixTpl metapod::Spatial::RotationMatrixTpl< FloatType >::transpose () const [inline]
References metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm, and metapod::Spatial::RotationMatrixTpl< FloatType >::RotationMatrixTpl().
Friends And Related Function Documentation
template<class FloatType > RotationMatrixTpl operator* (FloatType a, RotationMatrixTpl< FloatType > alti) [friend]
template<class FloatType > std::ostream& operator<< (std::ostream & os, const struct RotationMatrixTpl< FloatType > & aRMAX) [friend]
Member Data Documentation
template<class FloatType > metapod::Spatial::RotationMatrixTpl< FloatType >::EIGEN_METAPOD_TYPEDEFS
template<class FloatType > Matrix3d metapod::Spatial::RotationMatrixTpl< FloatType >::m_rm
Referenced by metapod::Spatial::RotationMatrixTpl< FloatType >::col(), metapod::Spatial::RotationMatrixTpl< FloatType >::operator()(), metapod::Spatial::RotationMatrixTpl< FloatType >::operator*(), metapod::Spatial::RotationMatrixTpl< FloatType >::operator-(), metapod::Spatial::RotationMatrixTpl< FloatType >::randomInit(), metapod::Spatial::RotationMatrixTpl< FloatType >::RotationMatrixTpl(), metapod::Spatial::RotationMatrixTpl< FloatType >::rotGeneralMatrix(), metapod::Spatial::RotationMatrixTpl< FloatType >::rotSymmetricMatrix(), metapod::Spatial::RotationMatrixTpl< FloatType >::rotTSymmetricMatrix(), metapod::Spatial::RotationMatrixTpl< FloatType >::setRotationMatrix(), metapod::Spatial::RotationMatrixTpl< FloatType >::toMatrix(), and metapod::Spatial::RotationMatrixTpl< FloatType >::transpose().