metapod::Spatial::TransformT< FloatType, RotationClass > Class Template Reference
metapod::Spatial::TransformT< FloatType, RotationClass > Class Template Reference
#include <metapod/tools/spatial/transform.hh>
Public Member Functions
TransformT ()
TransformT (const Matrix3d &E, const typename Vector3dTpl< FloatType >::Type &r)
TransformT (const RotationClass &E, const typename Vector3dTpl< FloatType >::Type &r)
Vector6dTpl< FloatType >::Type mulMatrixTransposeBy (typename Vector6dTpl< FloatType >::Type &aF) const
TransformT operator* (FloatType a) const
template<class S >
TransformT< FloatType,
typename rm_mul_op< FloatType,
RotationClass, S >::rm > operator* (const TransformT< FloatType, S > &aTsf) const
template<typename FloatType, typename RotationClass>
class metapod::Spatial::TransformT< FloatType, RotationClass >
Constructor & Destructor Documentation
template<typename FloatType, typename RotationClass> metapod::Spatial::TransformT< FloatType, RotationClass >::TransformT () [inline]
Referenced by metapod::Spatial::TransformT< FloatType, RotationClass >::operator*().
template<typename FloatType, typename RotationClass> metapod::Spatial::TransformT< FloatType, RotationClass >::TransformT (const Matrix3d & E, const typename Vector3dTpl< FloatType >::Type & r) [inline]
template<typename FloatType, typename RotationClass> metapod::Spatial::TransformT< FloatType, RotationClass >::TransformT (const RotationClass & E, const typename Vector3dTpl< FloatType >::Type & r) [inline]
Member Function Documentation
template<typename FloatType, typename RotationClass> Vector6dTpl<FloatType>::Type metapod::Spatial::TransformT< FloatType, RotationClass >::mulMatrixTransposeBy (typename Vector6dTpl< FloatType >::Type & aF) const [inline]
template<typename FloatType, typename RotationClass> TransformT metapod::Spatial::TransformT< FloatType, RotationClass >::operator* (FloatType a) const [inline]
References metapod::Spatial::TransformT< FloatType, RotationClass >::TransformT().
template<typename FloatType, typename RotationClass> template<class S > TransformT< FloatType, typename rm_mul_op<FloatType, RotationClass, S >::rm > metapod::Spatial::TransformT< FloatType, RotationClass >::operator* (const TransformT< FloatType, S > & aTsf) const [inline]
Reimplemented from metapod::Spatial::internal::TransformT_helper< FloatType, RotationClass >.
References metapod::Spatial::internal::TransformT_helper< FloatType, RotationClass >::E(), and metapod::Spatial::internal::TransformT_helper< FloatType, RotationClass >::r().