metapod::Spatial Namespace Reference
metapod::Spatial Namespace Reference
Namespaces
namespace Internal
Classes
class OperatorMul
class ConstraintMotionAnyAxis
class ConstraintMotionFreeFlyer
struct Vector6dMakerOneAxis
class ConstraintMotionOneAxis
class Force
class Inertia
class ltI
class Motion
struct RotationMatrixAboutX
RotationMatrixAboutX This object implements specific operations related to the rotation matrix about the X-axis:
struct RotationMatrixAboutY
RotationMatrixAboutY This object implements specific operations related to the rotation matrix about the Y-axis:
struct RotationMatrixAboutZ
RotationMatrixAboutZ This object implements specific operations related to the rotation matrix about the Z-axis:
struct RotationBinaryOp
struct rmca_traits
struct rmca_traits_mul
struct rmca_traits_transpose
struct rmca_traits_minus
struct RotationMatrixChangeAxis
Rotation matrix as axis permutation matrix.
struct RotationMatrix
struct RotationMatrixIdentity
struct rm_mul_op
This template implements the type conversion for the multiplication between rotation matrix.
struct rm_mul_op< op1, RotationMatrixIdentity >
Specializations.
struct rm_mul_op< RotationMatrixIdentity, op2 >
struct rm_mul_op< RotationMatrixAboutX, RotationMatrixAboutX >
struct rm_mul_op< RotationMatrixAboutY, RotationMatrixAboutY >
struct rm_mul_op< RotationMatrixAboutZ, RotationMatrixAboutZ >
class TransformT
Given two frames a and b, one can define the transform bXa, which changes coordinates between the two.
Typedefs
typedef
ConstraintMotionOneAxis< AxisX > ConstraintMotionAxisX
typedef
ConstraintMotionOneAxis< AxisY > ConstraintMotionAxisY
typedef
ConstraintMotionOneAxis< AxisZ > ConstraintMotionAxisZ
typedef ltI lowerTriangularMatrix
typedef TransformT
< RotationMatrix > Transform
typedef TransformT
< RotationMatrixAboutX > TransformX
typedef TransformT
< RotationMatrixAboutY > TransformY
typedef TransformT
< RotationMatrixAboutZ > TransformZ
typedef TransformT
< RotationMatrixIdentity > TransformId
Enumerations
enum AxisType {
AxisX = 0,
AxisY,
AxisZ
}
Functions
Motion sum (const Motion &mv1, const Motion &mv2, const Motion &mv3, const Motion &mv4)
Motion sum (const Motion &mv1, const Motion &mv2, const Motion &mv3)
Force sum (const Force &fv1, const Force &fv2, const Force &fv3)
Matrix3d skew (const Vector3d &v)
Implementation of a spatial algebra.
Vector6d operator* (const Inertia &m, const ConstraintMotionAnyAxis &a)
Matrix6d operator* (const Inertia &m, const ConstraintMotionFreeFlyer &a)
Vector6d operator* (const Inertia &m, const ConstraintMotionAxisX &)
Inertia operator* (const Inertia &m, const FloatType &a)
Force operator* (const Inertia &m, const Motion &mv)
Typedef Documentation
typedef ConstraintMotionOneAxis<AxisX> metapod::Spatial::ConstraintMotionAxisX
typedef ConstraintMotionOneAxis<AxisY> metapod::Spatial::ConstraintMotionAxisY
typedef ConstraintMotionOneAxis<AxisZ> metapod::Spatial::ConstraintMotionAxisZ
typedef ltI metapod::Spatial::lowerTriangularMatrix
typedef TransformT<RotationMatrix> metapod::Spatial::Transform
typedef TransformT<RotationMatrixIdentity> metapod::Spatial::TransformId
typedef TransformT<RotationMatrixAboutX> metapod::Spatial::TransformX
typedef TransformT<RotationMatrixAboutY> metapod::Spatial::TransformY
typedef TransformT<RotationMatrixAboutZ> metapod::Spatial::TransformZ
Enumeration Type Documentation
enum metapod::Spatial::AxisType
Enumerator:
AxisX
AxisY
AxisZ
Function Documentation
Vector6d metapod::Spatial::operator* (const Inertia & m, const ConstraintMotionAxisX &) [inline]
References metapod::Spatial::Inertia::h(), and metapod::Spatial::Inertia::I().
Matrix6d metapod::Spatial::operator* (const Inertia & m, const ConstraintMotionFreeFlyer & a) [inline]
References metapod::Spatial::OperatorMul< T, U, S >::mul().
Vector6d metapod::Spatial::operator* (const Inertia & m, const ConstraintMotionAnyAxis & a) [inline]
References metapod::Spatial::OperatorMul< T, U, S >::mul().
Inertia metapod::Spatial::operator* (const Inertia & m, const FloatType & a) [inline]
References metapod::Spatial::OperatorMul< T, U, S >::mul().
Force metapod::Spatial::operator* (const Inertia & m, const Motion & mv) [inline]
References metapod::Spatial::OperatorMul< T, U, S >::mul().
Matrix3d metapod::Spatial::skew (const Vector3d & v) [inline]
Implementation of a spatial algebra.
It follows R. Featherstone guidelines, and implements :
Spatial Motion vectors (a.k.a. twists)
Spatial Force vectors (a.k.a. wrenches)
Spatial Rigid Body Inertia matrices
Spatial Transforms (a.k.a. homogeneous matrices, elements of SE(3))
Referenced by metapod::Spatial::TransformT< RotationClass >::apply(), metapod::Spatial::TransformT< RotationClass >::applyInv(), metapod::FreeFlyerJoint::jcalc(), metapod::Spatial::OperatorMul< T, U, S >::mul(), metapod::Spatial::TransformT< RotationClass >::operator*(), metapod::internal::jac_point_chain_internal_freeflyer< Robot, start_node_id, end_node_id, offset, true >::run(), metapod::Spatial::Inertia::toMatrix(), metapod::Spatial::TransformT< RotationClass >::toMatrix(), metapod::Spatial::TransformT< RotationClass >::toMatrixTranspose(), and metapod::Spatial::TransformT< RotationClass >::toMatrixTransposeInverse().
Motion metapod::Spatial::sum (const Motion & mv1, const Motion & mv2, const Motion & mv3, const Motion & mv4) [inline]
References metapod::Spatial::Motion::v(), and metapod::Spatial::Motion::w().
Referenced by metapod::rnea< Robot, false >::DftVisitor< AnyRobot, node_id >::discover(), metapod::rnea< Robot, false >::update_kinematics< node_id, parent_id >::run(), and metapod::rnea< Robot, false >::update_kinematics< node_id, NO_PARENT >::run().
Motion metapod::Spatial::sum (const Motion & mv1, const Motion & mv2, const Motion & mv3) [inline]
References metapod::Spatial::Motion::v(), and metapod::Spatial::Motion::w().
Force metapod::Spatial::sum (const Force & fv1, const Force & fv2, const Force & fv3) [inline]
References metapod::Spatial::Force::f(), and metapod::Spatial::Force::n().