metapod Namespace Reference
metapod Namespace Reference
Templated Hybrid Dynamics Algorithm.
Namespaces
namespace internal
namespace Spatial
Classes
struct chda
struct crba
struct crba< Robot, false >
struct crba< Robot, true >
struct djac
struct jac
struct jac_point_chain
Point in Chain Articular Jacobian Algorithm.
struct jac_point_relative
struct rnea
Templated Recursive Newton-Euler Algorithm.
struct rnea< Robot, false, gravity >
struct rnea< Robot, true, gravity >
struct backward_traversal
struct backward_traversal< Visitor, Robot, end_node_id, end_node_id >
struct backward_traversal_previous
struct backward_traversal_prev
struct backward_traversal_prev< Visitor, Robot, end_node_id, end_node_id >
struct bcalc
class Body
struct Nodes
class GravityConstant
struct deepest_common_ancestor
Deepest common ancestor node of two nodes A and B. The member.
struct depth_first_traversal
struct Vector1dTpl
struct Vector3dTpl
struct Vector6dTpl
struct Vector6dtTpl
struct Matrix2dTpl
struct Matrix3_2dTpl
struct Matrix3dTpl
struct Matrix6dTpl
struct MatrixNTpl
struct VectorNTpl
struct is_NO_PARENT
value member variable is true if Node is NP (no parent), and false otherwise.
struct is_NO_PARENT< Robot, NO_PARENT >
struct myParent
type member variable is the parent node type of Node.
struct myParent< Robot, Node, false >
struct has_parent
value member variable is false if Node has no parent.
struct initConf
init a configuration vector with values from text file, formatted as printed by the printConf routine.
struct initConf< Robot, NOT_HYBRID, ConfTypeStreamOrVector >
struct initConf< Robot, HYBRID_DDQ, ConfTypeStreamOrVector >
struct initConf< Robot, HYBRID_TORQUES, ConfTypeStreamOrVector >
struct initNodeIdConf
Extracts the robot model node IDs into a configuration vector, as per node id to q_idx mapping.
struct initNodeIdConfReordRef
Extracts the robot model node IDs into a configuration vector.
struct initNuFwdDyn
init the "nuFwdDyn" parameter for Node's joint
struct is_ancestor
value member variable is true if NodeA is an ancestor of NodeB, false otherwise.
struct is_ancestor< Robot, node_a_id, node_a_id >
struct is_ancestor< Robot, node_a_id, NO_PARENT >
struct is_ancestor< Robot, NO_PARENT, NO_PARENT >
struct jac_point_robot
struct jcalc
class RevoluteAxisXJoint
class RevoluteAxisYJoint
class RevoluteAxisZJoint
class RevoluteAxisAnyJoint
class FreeFlyerJoint
struct qcalc
Enumerations
enum ConfType {
NOT_HYBRID = 0,
HYBRID_DDQ = 1,
HYBRID_TORQUES = 2
}
Functions
template<class FloatType >
struct Matrix3dTpl< FloatType >
::Type matrix3dMaker (FloatType m00, FloatType m01, FloatType m02, FloatType m10, FloatType m11, FloatType m12, FloatType m20, FloatType m21, FloatType m22)
template<class FloatType >
struct Vector6dTpl< FloatType >
::Type vector6dMaker (FloatType v0, FloatType v1, FloatType v2, FloatType v3, FloatType v4, FloatType v5)
template<typename FloatType , int gravity>
Spatial::MotionTpl< FloatType > set_gravity ()
template<typename FloatType >
class Matrix3dTpl< FloatType >
::Type Skew (const class Vector3dTpl< FloatType >::Type &v)
template<typename FloatType >
Spatial::InertiaTpl< FloatType > spatialInertiaMaker (const FloatType m, const class Vector3dTpl< FloatType >::Type &CoM, const class Matrix3dTpl< FloatType >::Type &inertia)
template<typename Robot >
void printState (const Robot &robot, std::ostream &os)
template<typename Robot >
void printConf (const struct VectorNTpl< typename Robot::RobotFloatType >::Type &q, std::ostream &os)
template<typename Robot >
void printNuFwdDyn (std::ostream &os, std::ostream &refOs)
template<typename Robot >
void printTransforms (const Robot &robot, std::ostream &os)
template<typename Robot >
void printTorques (Robot &robot, std::ostream &os)
template<typename Robot >
void getTorques (Robot &robot, typename Robot::confVector &v)
Variables
static const int MAX_NB_JOINTS = 50
static const int MAX_NB_CHILDREN_PER_NODE = 5
static const int NO_PARENT = -1
static const int NO_CHILD = -2
static const int NO_NODE = -3
Detailed Description
Templated Hybrid Dynamics Algorithm.
Implementation of an algorithm that checks whether a node is an ancestor of another one or not.
Implementation of two algorithms that check whether a node is NP (no parent) or not and if it has a parent or not.
Implementation of an algorithm that computes the deepest common ancestor of two nodes.
Implementation of articular jacobian of point given an influencing chain of joints.
Compute the kinematic jacobian.
Compute the derivative of the kinematic jacobian.
Takes the multibody tree type as template parameter, and recursively proceeds on the Nodes.
i.e. the matrix J such that J*dq is the vertical concatenation of each body spatial motion vector (in the moving body frame)
Enumeration Type Documentation
enum metapod::ConfType
Enumerator:
NOT_HYBRID
HYBRID_DDQ
HYBRID_TORQUES
Function Documentation
template<typename Robot > void metapod::getTorques (Robot & robot, typename Robot::confVector & v)
References metapod::depth_first_traversal< Visitor, Robot >::run().
Referenced by metapod::internal::chda_internal< Robot, jcalc, gravity, NBDOF, nbFdDOF >::run(), metapod::internal::chda_internal< Robot, jcalc, gravity, NBDOF, 0 >::run(), and metapod::internal::chda_internal< Robot, jcalc, gravity, NBDOF, NBDOF >::run().
template<class FloatType > struct Matrix3dTpl< FloatType >::Type metapod::matrix3dMaker (FloatType m00, FloatType m01, FloatType m02, FloatType m10, FloatType m11, FloatType m12, FloatType m20, FloatType m21, FloatType m22) [read]
template<typename Robot > void metapod::printConf (const struct VectorNTpl< typename Robot::RobotFloatType >::Type & q, std::ostream & os)
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<typename Robot > void metapod::printNuFwdDyn (std::ostream & os, std::ostream & refOs)
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<typename Robot > void metapod::printState (const Robot & robot, std::ostream & os)
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<typename Robot > void metapod::printTorques (Robot & robot, std::ostream & os)
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<typename Robot > void metapod::printTransforms (const Robot & robot, std::ostream & os)
References metapod::depth_first_traversal< Visitor, Robot >::run().
template<typename FloatType , int gravity> Spatial::MotionTpl<FloatType> metapod::set_gravity () [inline]
template<typename FloatType > class Matrix3dTpl< FloatType >::Type metapod::Skew (const class Vector3dTpl< FloatType >::Type & v) [inline]
template<typename FloatType > Spatial::InertiaTpl<FloatType> metapod::spatialInertiaMaker (const FloatType m, const class Vector3dTpl< FloatType >::Type & CoM, const class Matrix3dTpl< FloatType >::Type & inertia) [inline]
template<class FloatType > struct Vector6dTpl< FloatType >::Type metapod::vector6dMaker (FloatType v0, FloatType v1, FloatType v2, FloatType v3, FloatType v4, FloatType v5) [read]
References EIGEN_METAPOD_TYPEDEFS.
Variable Documentation
const int metapod::MAX_NB_CHILDREN_PER_NODE = 5 [static]
const int metapod::MAX_NB_JOINTS = 50 [static]
const int metapod::NO_CHILD = -2 [static]
const int metapod::NO_NODE = -3 [static]
const int metapod::NO_PARENT = -1 [static]