metapod::Spatial Namespace Reference
metapod::Spatial Namespace Reference
Namespaces
namespace internal
namespace Internal
Classes
class ConstraintMotionAnyAxis
class ConstraintMotionAnyAxis< FloatType >
class ConstraintMotionFreeFlyerTpl
struct Vector6dMakerOneAxis
class ConstraintMotionOneAxis
struct ConstraintMotionAxisXTpl
struct ConstraintMotionAxisYTpl
struct ConstraintMotionAxisZTpl
class ForceTpl
class InertiaTpl
class ltI
class MotionTpl
struct RotationMatrixAboutXTpl
RotationMatrixAboutX This object implements specific operations related to the rotation matrix about the X-axis:
struct RotationMatrixAboutYTpl
RotationMatrixAboutY This object implements specific operations related to the rotation matrix about the Y-axis:
struct RotationMatrixAboutZTpl
RotationMatrixAboutZ This object implements specific operations related to the rotation matrix about the Z-axis:
struct RotationBinaryOp
struct rmca_traits
struct rmca_traits_mul
struct rmca_traits_transpose
struct rmca_traits_minus
class RotationMatrixChangeAxisTpl
Rotation matrix as axis permutation matrix.
struct RotationMatrixTpl
struct RotationMatrixIdentityTpl
struct rm_mul_op
This template implements the type conversion for the multiplication between rotation matrix.
struct rm_mul_op< FloatType, op1, RotationMatrixIdentityTpl< FloatType > >
Specializations.
struct rm_mul_op< FloatType, RotationMatrixIdentityTpl< FloatType >, op2 >
struct rm_mul_op< FloatType, RotationMatrixAboutXTpl< FloatType >, RotationMatrixAboutXTpl< FloatType > >
struct rm_mul_op< FloatType, RotationMatrixAboutYTpl< FloatType >, RotationMatrixAboutYTpl< FloatType > >
struct rm_mul_op< FloatType, RotationMatrixAboutZTpl< FloatType >, RotationMatrixAboutZTpl< FloatType > >
class TransformT
class TransformT< FloatType, RotationMatrixAboutXTpl< FloatType > >
class TransformT< FloatType, RotationMatrixAboutYTpl< FloatType > >
class TransformT< FloatType, RotationMatrixAboutZTpl< FloatType > >
class TransformT< FloatType, RotationMatrixTpl< FloatType > >
Enumerations
enum AxisType {
AxisX = 0,
AxisY,
AxisZ
}
Functions
template<typename FloatType >
MotionTpl< FloatType > sum (const MotionTpl< FloatType > &mv1, const MotionTpl< FloatType > &mv2, const MotionTpl< FloatType > &mv3, const MotionTpl< FloatType > &mv4)
template<typename FloatType >
MotionTpl< FloatType > sum (const MotionTpl< FloatType > &mv1, const MotionTpl< FloatType > &mv2, const MotionTpl< FloatType > &mv3)
template<typename FloatType >
ForceTpl< FloatType > sum (const ForceTpl< FloatType > &fv1, const ForceTpl< FloatType > &fv2, const ForceTpl< FloatType > &fv3)
template<typename FloatType >
Matrix3dTpl< FloatType >::Type skew (const typename Vector3dTpl< FloatType >::Type &v)
Implementation of a spatial algebra.
template<class FloatType >
metapod::Spatial::ConstraintMotionAnyAxis
< FloatType > operator
doublexconst operator (const InertiaTpl< FloatType > &m, const ConstraintMotionAnyAxis< FloatType > &a)
template<class FloatType >
class Vector6dTpl< FloatType >
::Type operator^ (const MotionTpl< FloatType > &m, const ConstraintMotionAnyAxis< FloatType > &a)
Cross operator between motion and constraint motion free flyer.
template<class FloatType >
class Matrix6dTpl< FloatType >
::Type operator* (const InertiaTpl< FloatType > &m, const ConstraintMotionFreeFlyerTpl< FloatType > &a)
template<class FloatType >
class Matrix6dTpl< FloatType >
::Type operator^ (const MotionTpl< FloatType > &m, const ConstraintMotionFreeFlyerTpl< FloatType > &a)
Cross operator between motion and constraint motion free flyer.
template<class FloatType >
class Vector6dTpl< FloatType >
::Type operator* (const InertiaTpl< FloatType > &m, const struct ConstraintMotionAxisXTpl< FloatType >::Type &)
template<class FloatType >
class Vector6dTpl< FloatType >
::Type operator* (const InertiaTpl< FloatType > &m, const struct ConstraintMotionAxisYTpl< FloatType >::Type &)
template<class FloatType >
class Vector6dTpl< FloatType >
::Type operator* (const InertiaTpl< FloatType > &m, const struct ConstraintMotionAxisZTpl< FloatType >::Type &)
template<class FloatType >
class Vector6dTpl< FloatType >
::Type operator^ (const MotionTpl< FloatType > &m, const struct ConstraintMotionAxisXTpl< FloatType >::Type &)
template<class FloatType >
class Vector6dTpl< FloatType >
::Type operator^ (const MotionTpl< FloatType > &m, const struct ConstraintMotionAxisYTpl< FloatType >::Type &)
template<class FloatType >
class Vector6dTpl< FloatType >
::Type operator^ (const MotionTpl< FloatType > &m, const struct ConstraintMotionAxisZTpl< FloatType >::Type &)
template<class FloatType >
std::ostream & operator<< (std::ostream &os, const InertiaTpl< FloatType > &I)
template<class FloatType >
InertiaTpl< FloatType > operator* (FloatType a, const InertiaTpl< FloatType > &I)
template<class FloatType >
ltI< FloatType > operator* (FloatType a, const ltI< FloatType > &altI)
Variables
class
metapod::Spatial::ConstraintMotionFreeFlyerTpl operator
Enumeration Type Documentation
enum metapod::Spatial::AxisType
Enumerator:
AxisX
AxisY
AxisZ
Function Documentation
template<class FloatType > metapod::Spatial::ConstraintMotionAnyAxis< FloatType > operator doublexconst metapod::Spatial::operator (const InertiaTpl< FloatType > & m, const ConstraintMotionAnyAxis< FloatType > & a)
template<class FloatType > class Matrix6dTpl< FloatType >::Type metapod::Spatial::operator* (const InertiaTpl< FloatType > & m, const ConstraintMotionFreeFlyerTpl< FloatType > & a) [inline]
References EIGEN_METAPOD_TYPEDEFS.
template<class FloatType > class Vector6dTpl< FloatType >::Type metapod::Spatial::operator* (const InertiaTpl< FloatType > & m, const struct ConstraintMotionAxisXTpl< FloatType >::Type &) [inline]
References EIGEN_METAPOD_TYPEDEFS.
template<class FloatType > class Vector6dTpl< FloatType >::Type metapod::Spatial::operator* (const InertiaTpl< FloatType > & m, const struct ConstraintMotionAxisYTpl< FloatType >::Type &) [inline]
References EIGEN_METAPOD_TYPEDEFS.
template<class FloatType > class Vector6dTpl< FloatType >::Type metapod::Spatial::operator* (const InertiaTpl< FloatType > & m, const struct ConstraintMotionAxisZTpl< FloatType >::Type &) [inline]
References EIGEN_METAPOD_TYPEDEFS.
template<class FloatType > InertiaTpl<FloatType> metapod::Spatial::operator* (FloatType a, const InertiaTpl< FloatType > & I) [inline]
template<class FloatType > ltI<FloatType> metapod::Spatial::operator* (FloatType a, const ltI< FloatType > & altI) [inline]
template<class FloatType > std::ostream& metapod::Spatial::operator<< (std::ostream & os, const InertiaTpl< FloatType > & I) [inline]
template<class FloatType > class Matrix6dTpl< FloatType >::Type metapod::Spatial::operator^ (const MotionTpl< FloatType > & m, const ConstraintMotionFreeFlyerTpl< FloatType > & a) [inline]
Cross operator between motion and constraint motion free flyer.
References EIGEN_METAPOD_TYPEDEFS.
template<class FloatType > class Vector6dTpl< FloatType >::Type metapod::Spatial::operator^ (const MotionTpl< FloatType > & m, const ConstraintMotionAnyAxis< FloatType > & a) [inline]
Cross operator between motion and constraint motion free flyer.
References EIGEN_METAPOD_TYPEDEFS, and segment< 3 >().
template<class FloatType > class Vector6dTpl< FloatType >::Type metapod::Spatial::operator^ (const MotionTpl< FloatType > & m, const struct ConstraintMotionAxisXTpl< FloatType >::Type &) [inline]
References EIGEN_METAPOD_TYPEDEFS.
template<class FloatType > class Vector6dTpl< FloatType >::Type metapod::Spatial::operator^ (const MotionTpl< FloatType > & m, const struct ConstraintMotionAxisYTpl< FloatType >::Type &) [inline]
References EIGEN_METAPOD_TYPEDEFS.
template<class FloatType > class Vector6dTpl< FloatType >::Type metapod::Spatial::operator^ (const MotionTpl< FloatType > & m, const struct ConstraintMotionAxisZTpl< FloatType >::Type &) [inline]
References EIGEN_METAPOD_TYPEDEFS.
template<typename FloatType > Matrix3dTpl<FloatType>::Type metapod::Spatial::skew (const typename Vector3dTpl< FloatType >::Type & v) [inline]
Implementation of a spatial algebra.
It follows R. Featherstone guidelines, and implements :
Spatial Motion vectors (a.k.a. twists)
Spatial Force vectors (a.k.a. wrenches)
Spatial Rigid Body Inertia matrices
Spatial Transforms (a.k.a. homogeneous matrices, elements of SE(3))
References EIGEN_METAPOD_TYPEDEFS.
Referenced by metapod::Spatial::internal::TransformT_helper< FloatType, RotationMatrixAboutZTpl< FloatType > >::operator*(), metapod::Spatial::InertiaTpl< FloatType >::toMatrix(), metapod::Spatial::internal::TransformT_helper< FloatType, RotationMatrixAboutZTpl< FloatType > >::toMatrixTranspose(), and metapod::Spatial::internal::TransformT_helper< FloatType, RotationMatrixAboutZTpl< FloatType > >::toMatrixTransposeInverse().
template<typename FloatType > MotionTpl<FloatType> metapod::Spatial::sum (const MotionTpl< FloatType > & mv1, const MotionTpl< FloatType > & mv2, const MotionTpl< FloatType > & mv3, const MotionTpl< FloatType > & mv4) [inline]
References metapod::Spatial::MotionTpl< FloatType >::v(), and metapod::Spatial::MotionTpl< FloatType >::w().
Referenced by metapod::rnea< Robot, false, gravity >::DftVisitor< AnyRobot, node_id >::discover(), metapod::rnea< Robot, false, gravity >::update_kinematics< node_id, parent_id >::run(), and metapod::rnea< Robot, false, gravity >::update_kinematics< node_id, NO_PARENT >::run().
template<typename FloatType > MotionTpl<FloatType> metapod::Spatial::sum (const MotionTpl< FloatType > & mv1, const MotionTpl< FloatType > & mv2, const MotionTpl< FloatType > & mv3) [inline]
References metapod::Spatial::MotionTpl< FloatType >::v(), and metapod::Spatial::MotionTpl< FloatType >::w().
template<typename FloatType > ForceTpl<FloatType> metapod::Spatial::sum (const ForceTpl< FloatType > & fv1, const ForceTpl< FloatType > & fv2, const ForceTpl< FloatType > & fv3) [inline]
References metapod::Spatial::ForceTpl< FloatType >::f(), and metapod::Spatial::ForceTpl< FloatType >::n().
Variable Documentation
class metapod::Spatial::ConstraintMotionFreeFlyerTpl metapod::Spatial::operator